# Dokumentacja PySpark

Strona z opisem funkcjonalności: https://spark.apache.org/docs/latest/api/python/index.html

Link do dokumentacji: https://spark.apache.org/docs/latest/api/python/getting_started/index.html


### Apache Spark

Apache Spark to szybki i uniwersalny silnik przetwarzania danych, który umożliwia łatwe przetwarzanie dużych zbiorów danych równolegle. PySpark jest interfejsem Pythona do Sparka, co pozwala na korzystanie z jego możliwości w środowisku Pythona.

Rozproszenie środowiska w PySpark odnosi się do zdolności do równoczesnego przetwarzania dużych zbiorów danych na wielu węzłach klastra. Spark automatycznie dzieli dane na części i przetwarza je równolegle na różnych węzłach, co przyspiesza przetwarzanie w porównaniu do tradycyjnych podejść jednowęzłowych.

### Jak jest to realizowane?

* RDD (Resilient Distributed Datasets):

Podstawowa abstrakcja danych w Sparku, reprezentuje podzbiór danych równocześnie na wielu węzłach klastra. Każdy RDD jest podzielony na wiele partycji, które są przetwarzane niezależnie.

```
from pyspark import SparkContext

sc = SparkContext("local", "ExampleApp")
data = [1, 2, 3, 4, 5]
rdd = sc.parallelize(data, 2)  # Drugi argument to liczba partycji
```

* DataFrame:


Abstrakcja danych, bardziej wysokopoziomowa niż RDD, umożliwiająca pracę z danymi w formie tabelarycznej. Działa na zasadzie partycji podobnie jak RDD, ale dostarcza bardziej rozbudowanego interfejsu.

```
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("ExampleApp").getOrCreate()
df = spark.createDataFrame([(1, "John"), (2, "Jane"), (3, "Doe")], ["id", "name"])
```

* Zadania Transformacji i Akcji:

Transformacje definiują nowe RDD/DataFrame na podstawie istniejących danych.
Akcje wykonują operacje na danych i zwracają wynik do lokalnego środowiska.

### O czym należy pamiętać?

* Liczba Partycji: Optymalna liczba partycji zależy od wielkości danych, dostępnych zasobów klastra i rodzaju operacji. Zbyt mała liczba partycji może prowadzić do niewydajnego przetwarzania, podczas gdy zbyt duża liczba partycji może prowadzić do nadmiernego narzutu komunikacyjnego.

* Równomierny Rozkład Danych: Należy pamietać, by zapewnić, aby dane były równomiernie rozdzielone między partycje. Nierównomierność może prowadzić do wydłużonego czasu przetwarzania z powodu pracy "węża gardłowego" na jednej z partycji.

* Optymalizacja Operacji: Należy unikać zbierania dużych ilości danych do lokalnego środowiska (`collect()`), jeśli to możliwe, ponieważ może to prowadzić do przeciążenia pamięci na lokalnym środowisku.

* Użycie Funkcji Spark: Warto korzystać z wbudowanych funkcji Spark, takich jak operacje map, filter, reduce, które są optymalizowane pod kątem równoległego przetwarzania.

```
# Przykład operacji MapReduce
lines = sc.textFile("path/to/textfile.txt")
word_counts = lines.flatMap(lambda line: line.split(" ")).map(lambda word: (word, 1)).reduceByKey(lambda a, b: a + b)
```

1. Zasoby Klastra:

Monitoruj dostępność zasobów klastra, takich jak liczba rdzeni CPU, dostępna pamięć, aby zoptymalizować równoczesność przetwarzania.

2. Optymalizacja Planu Wykonawczego:

Spark automatycznie optymalizuje plany wykonawcze, ale można ręcznie dostosować niektóre ustawienia, takie jak partycje i cache, aby zoptymalizować wydajność.

```
# Przykład ręcznej optymalizacji liczby partycji
rdd = rdd.repartition(4)
```

Zrozumienie i odpowiednie uwzględnienie tych aspektów jest kluczowe dla efektywnego korzystania z rozproszonego środowiska w PySpark.

## Funkcje PySpark:
1. RDD (Resilient Distributed Datasets):

Podstawowa abstrakcja danych w Sparku.
Elastyczne, odpornie na awarie struktury danych, które można łatwo dystrybuować na wiele węzłów.

In [ ]:
from pyspark import SparkContext

sc = SparkContext("local", "MyApp")
data = [1, 2, 3, 4, 5]
rdd = sc.parallelize(data)

2. DataFrame:

Struktura danych podobna do tabeli w bazie danych.
Umożliwia łatwe przetwarzanie danych przy użyciu SQL queries.

In [ ]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("MyApp").getOrCreate()
df = spark.createDataFrame([(1, "John"), (2, "Jane")], ["id", "name"])

Metoda `collect()` w PySpark jest używana do zebrania wszystkich elementów DataFrame z rozproszonego środowiska do lokalnego środowiska (driver program). Jednak, warto zauważyć, że ta operacja może być kosztowna, ponieważ wymaga przesłania wszystkich danych z klastra do jednego punktu, co może być wydajnościowo kosztowne w przypadku dużych zbiorów danych.

In [ ]:
# Składnia
data = df.collect()

# Utwórz sesję Spark
spark = SparkSession.builder.appName("CollectExample").getOrCreate()

# Przykładowe dane
data = [(1, "John"), (2, "Jane"), (3, "Doe")]
columns = ["id", "name"]

# Utwórz DataFrame
df = spark.createDataFrame(data, columns)

# Wykonaj operację collect
collected_data = df.collect()

# Wyświetl zebrane dane
for row in collected_data:
    print(row)

W powyższym przykładzie, `collect()` zebrał dane DataFrame `df` do listy obiektów `Row`, a następnie te dane zostały wypisane. Dla dużych zbiorów danych `collect()` może prowadzić do przeciążenia pamięci na lokalnym środowisku, więc zaleca się ostrożność przy jej używaniu. W praktyce, często lepszym podejściem jest wykonywanie operacji na rozproszonych danych w samym środowisku Spark bez konieczności ich zbierania do lokalnego środowiska.

3. Operacje Transformacji i Akcji:


Transformacje definiują nowe RDD/DataFrame na podstawie istniejących danych.
Akcje wykonują operacje na danych i zwracają wynik do lokalnego środowiska.

In [ ]:
# Transformacja
mapped_rdd = rdd.map(lambda x: x * 2)

# Akcja
result = mapped_rdd.reduce(lambda x, y: x + y)

### Algorytmy Przetwarzania Danych:

1. Machine Learning:


PySpark oferuje bogaty zestaw algorytmów ML dla klasyfikacji, regresji, klastrowania, etc.

In [ ]:
from pyspark.ml.classification import LogisticRegression

# Przykład klasyfikacji
lr = LogisticRegression(maxIter=10, regParam=0.01)
model = lr.fit(train_data)

2. GraphX:


Biblioteka do przetwarzania grafów, co jest użyteczne w analizie sieci społecznościowej, trasowania itp.

In [ ]:
from pyspark.sql import SparkSession
from graphframes import GraphFrame

# Tworzenie grafu
vertices = spark.createDataFrame([(1, "A"), (2, "B"), (3, "C")], ["id", "name"])
edges = spark.createDataFrame([(1, 2, "friend"), (2, 3, "follow")], ["src", "dst", "relationship"])

g = GraphFrame(vertices, edges)

### Analiza Danych:

1. SQL w PySpark:

Możliwość przetwarzania danych za pomocą zapytań SQL.

In [ ]:
# Tworzenie tymczasowej tabeli
df.createOrReplaceTempView("my_table")

# Przykład zapytania SQL
result_df = spark.sql("SELECT id, name FROM my_table WHERE id > 1")

2. Wizualizacja Danych:


Możliwość korzystania z narzędzi do wizualizacji danych, takich jak Matplotlib, Seaborn.

In [ ]:
import matplotlib.pyplot as plt

# Przykład wykresu
plt.scatter(df.select("feature1").collect(), df.select("feature2").collect())
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.show()

PySpark to potężne narzędzie do przetwarzania danych, oferujące wiele funkcji i algorytmów. Dzięki elastycznym strukturom danych i obszernej funkcjonalności analizy danych, PySpark staje się niezastąpionym narzędziem w ekosystemie big data.

### Konfiguracja sesji PySpark

Personalizacja ustawień sesji PySpark odbywa się poprzez konfigurację SparkSession. Możesz dostosować różne parametry, takie jak liczba rdzeni, pamięć, ustawienia SQL, itp. Oto kilka przykładów różnych parametrów i jak można je konfigurować:

1. Liczba Rdzeni (Cores): `config("spark.cores.max", "4")`
Parametr "spark.cores.max" określa maksymalną liczbę rdzeni, które mogą być używane przez Spark. W powyższym przykładzie ustawiono maksymalną liczbę rdzeni na 4.

2. Ustawienia Pamięci:  `config("spark.executor.memory", "2g").config("spark.driver.memory", "1g")`
Parametry "spark.executor.memory" i "spark.driver.memory" pozwalają na ustawienie ilości dostępnej pamięci dla executorów i drivera, odpowiednio. W powyższym przykładzie ustawiono 2 GB pamięci dla executorów i 1 GB dla drivera.

3. Ustawienia SQL: `config("spark.sql.shuffle.partitions", "10").config("spark.sql.autoBroadcastJoinThreshold", "52428800")`
Parametr "spark.sql.shuffle.partitions" określa liczbę partycji do użycia w operacjach shuffle, a "spark.sql.autoBroadcastJoinThreshold" ustala maksymalny rozmiar tabeli do automatycznego rozgłaszania (broadcast join). W powyższym przykładzie ustawiono 10 partycji dla shuffle i próg automatycznego rozgłaszania na 50 MB.

4. Inne Ustawienia: `config("spark.streaming.stopGracefullyOnShutdown", "true").config("spark.executor.instances", "2")`
Parametr "spark.streaming.stopGracefullyOnShutdown" pozwala na kontrolowanie czy stopować strumieniowanie z gracji podczas zamykania aplikacji. Parametr "spark.executor.instances" ustawia liczbę instancji executorów w trybie rozproszonym.

5. Ustawienia Loggera: `config("spark.driver.extraJavaOptions", "-Dlog4j.configuration=file:log4j.properties")`
Parametr "spark.driver.extraJavaOptions" pozwala na dostosowanie konfiguracji log4j dla drivera Sparka.

### Warto pamiętać:
* Parametry można łączyć w jednym łańcuchu konfiguracji, używając metody config wielokrotnie.
* Bardzo ważne jest dostosowanie tych parametrów do wymagań konkretnego zadania lub aplikacji w celu uzyskania optymalnej wydajności.

# Instalacja frameworka PySpark w środowisku

In [7]:
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q http://archive.apache.org/dist/spark/spark-3.1.1/spark-3.1.1-bin-hadoop3.2.tgz
!tar xf spark-3.1.1-bin-hadoop3.2.tgz
!pip install -q findspark

Ustawianie ścieżki do folderu Spark

In [8]:
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.1.1-bin-hadoop3.2"

Import bibliotek

In [10]:
import findspark
findspark.init()
import pandas as pd
from pyspark.sql import SparkSession
from pyspark.context import SparkContext
from pyspark.sql.functions import *
from pyspark.sql.types import *

### Tworzenie sesji Spark

W PySpark, sesja jest głównym punktem wejścia dla programów opartych na Sparku, umożliwiając interakcję z rozproszonymi danymi. Sesję PySpark można utworzyć przy użyciu obiektu `SparkSession`, który łączy różne konteksty pracy w jedno środowisko. Tworzenie sesji jest ważne, ponieważ dostarcza środowisko wykonawcze dla aplikacji PySpark oraz konfiguruje różne ustawienia, takie jak ustawienia klastra, ustawienia aplikacji itp.

In [11]:
# Utwórz obiekt SparkSession
session = SparkSession.builder.appName('myApp').getOrCreate() # creating a session

session

Wartością zwracaną przez `getOrCreate()` jest istniejąca sesja Spark, jeśli już istnieje, lub nowo utworzona sesja, jeśli nie. Dzięki temu możemy bezpiecznie korzystać z jednej sesji w naszej aplikacji.

### Dlaczego Tworzymy Sesję PySpark?

* Środowisko Wykonawcze: Sesja dostarcza środowisko wykonawcze dla aplikacji PySpark, zarządzając dostępem do zasobów klastra.

* Konfiguracje Aplikacji: Pozwala na dostosowanie konfiguracji aplikacji, takich jak liczba rdzeni, ilość pamięci itp.

* Ustawienia Aplikacji: Możemy dostarczyć unikalne nazwy aplikacji, co ułatwia identyfikację zadań w klastrze.

* Integracja z Biblioteką Spark SQL: Umożliwia korzystanie z funkcji Spark SQL, takich jak przetwarzanie danych za pomocą SQL, tworzenie DataFrame itp.

* Optymalizacja Wydajności: Sesja pozwala na dostosowanie ustawień dla optymalizacji wydajności w zależności od specyfiki aplikacji.


Przykład wykorzystania sesji PySpark w kontekście wczytywania danych:

In [ ]:
# Wczytaj dane do DataFrame
df = spark.read.csv("path/to/data.csv", header=True, inferSchema=True)

# Wykonaj operacje na danych
result = df.groupBy("column").agg({"other_column": "mean"})

# Wyświetl wyniki
result.show()

W powyższym przykładzie, spark to obiekt sesji, który umożliwia wczytywanie danych, przetwarzanie ich za pomocą operacji na DataFrame, a następnie wyświetlanie wyników. Sesja jest kluczowym elementem do efektywnego korzystania z PySpark w analizie danych na dużą skalę.

### Pobranie plików i załadowanie ich do środowiska

Dane z linku: https://github.com/datasciencedojo/datasets/blob/master/titanic.csv

Plik pobrać i umieścić w swojej chmurze google by uzyskać dostęp do pliku w Jupter Notebook ColabResearch. Po lewej stronie znajduje się ikona folderu, na którą należy nacisnąć, a następnie wybrać pierwszą ikonę na górze po lewej stronie, za pomocą której można umieścić w obszarze roboczym pobrany plik.


Innym sposobem na upload plików jest wykorzystanie poniższej instrukcji, gdzie po uruchomieniu komórki należy nacisnąć wybierz pliki i wskazać na pobrany plik. Załaduje się on do tymczasowego obszaru roboczego, do którego będziemy mieli dostęp

In [ ]:
from google.colab import files
files.upload()

Saving titanic.csv to titanic (1).csv

{'titanic (1).csv': b'PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked\n1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,,S\n2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38,1,0,PC 17599,71.2833,C85,C\n3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,,S\n4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S\n5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.05,,S\n6,0,3,"Moran, Mr. James",male,,0,0,330877,8.4583,,Q\n7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625,E46,S\n8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.075,,S\n9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.1333,,S\n10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.0708,,C\n11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4,1,1,PP 9549,16.7,G6,S\n12,1,1,"Bonnell, Miss. Elizabeth",female,58,0,0,113783,26.55,C103,S\n13,0,3,"Saundercock, Mr. William Henry",male,20,0,0,A/5. 2151,8.05,,S\n14,0,3,"Andersson, Mr. Anders Johan",male,39,1,5,347082,31.275,,S\n15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14,0,0,350406,7.8542,,S\n16,1,2,"Hewlett, Mrs. (Mary D Kingcome) ",female,55,0,0,248706,16,,S\n17,0,3,"Rice, Master. Eugene",male,2,4,1,382652,29.125,,Q\n18,1,2,"Williams, Mr. Charles Eugene",male,,0,0,244373,13,,S\n19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)",female,31,1,0,345763,18,,S\n20,1,3,"Masselmani, Mrs. Fatima",female,,0,0,2649,7.225,,C\n21,0,2,"Fynney, Mr. Joseph J",male,35,0,0,239865,26,,S\n22,1,2,"Beesley, Mr. Lawrence",male,34,0,0,248698,13,D56,S\n23,1,3,"McGowan, Miss. Anna ""Annie""",female,15,0,0,330923,8.0292,,Q\n24,1,1,"Sloper, Mr. William Thompson",male,28,0,0,113788,35.5,A6,S\n25,0,3,"Palsson, Miss. Torborg Danira",female,8,3,1,349909,21.075,,S\n26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)",female,38,1,5,347077,31.3875,,S\n27,0,3,"Emir, Mr. Farred Chehab",male,,0,0,2631,7.225,,C\n28,0,1,"Fortune, Mr. Charles Alexander",male,19,3,2,19950,263,C23 C25 C27,S\n29,1,3,"O\'Dwyer, Miss. Ellen ""Nellie""",female,,0,0,330959,7.8792,,Q\n30,0,3,"Todoroff, Mr. Lalio",male,,0,0,349216,7.8958,,S\n31,0,1,"Uruchurtu, Don. Manuel E",male,40,0,0,PC 17601,27.7208,,C\n32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,,1,0,PC 17569,146.5208,B78,C\n33,1,3,"Glynn, Miss. Mary Agatha",female,,0,0,335677,7.75,,Q\n34,0,2,"Wheadon, Mr. Edward H",male,66,0,0,C.A. 24579,10.5,,S\n35,0,1,"Meyer, Mr. Edgar Joseph",male,28,1,0,PC 17604,82.1708,,C\n36,0,1,"Holverson, Mr. Alexander Oskar",male,42,1,0,113789,52,,S\n37,1,3,"Mamee, Mr. Hanna",male,,0,0,2677,7.2292,,C\n38,0,3,"Cann, Mr. Ernest Charles",male,21,0,0,A./5. 2152,8.05,,S\n39,0,3,"Vander Planke, Miss. Augusta Maria",female,18,2,0,345764,18,,S\n40,1,3,"Nicola-Yarred, Miss. Jamila",female,14,1,0,2651,11.2417,,C\n41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40,1,0,7546,9.475,,S\n42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)",female,27,1,0,11668,21,,S\n43,0,3,"Kraeff, Mr. Theodor",male,,0,0,349253,7.8958,,C\n44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3,1,2,SC/Paris 2123,41.5792,,C\n45,1,3,"Devaney, Miss. Margaret Delia",female,19,0,0,330958,7.8792,,Q\n46,0,3,"Rogers, Mr. William John",male,,0,0,S.C./A.4. 23567,8.05,,S\n47,0,3,"Lennon, Mr. Denis",male,,1,0,370371,15.5,,Q\n48,1,3,"O\'Driscoll, Miss. Bridget",female,,0,0,14311,7.75,,Q\n49,0,3,"Samaan, Mr. Youssef",male,,2,0,2662,21.6792,,C\n50,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18,1,0,349237,17.8,,S\n51,0,3,"Panula, Master. Juha Niilo",male,7,4,1,3101295,39.6875,,S\n52,0,3,"Nosworthy, Mr. Richard Cater",male,21,0,0,A/4. 39886,7.8,,S\n53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49,1,0,PC 17572,76.7292,D33,C\n54,1,2,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)",female,29,1,0,2926,26,,S\n55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65,0,1,113509,61.9792,B30,C\n56,1,1,"Woolner, Mr. Hugh",male,,0,0,19947,35.5,C52,S\n57,1,2,"Rugg, Miss. Emily",female,21,0,0,C.A. 31026,10.5,,S\n58,0,3,"Novel, Mr. Mansouer",male,28.5,0,0,2697,7.2292,,C\n59,1,2,"West, Miss. Constance Mirium",female,5,1,2,C.A. 34651,27.75,,S\n60,0,3,"Goodwin, Master. William Frederick",male,11,5,2,CA 2144,46.9,,S\n61,0,3,"Sirayanian, Mr. Orsen",male,22,0,0,2669,7.2292,,C\n62,1,1,"Icard, Miss. Amelie",female,38,0,0,113572,80,B28,\n63,0,1,"Harris, Mr. Henry Birkhardt",male,45,1,0,36973,83.475,C83,S\n64,0,3,"Skoog, Master. Harald",male,4,3,2,347088,27.9,,S\n65,0,1,"Stewart, Mr. Albert A",male,,0,0,PC 17605,27.7208,,C\n66,1,3,"Moubarek, Master. Gerios",male,,1,1,2661,15.2458,,C\n67,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29,0,0,C.A. 29395,10.5,F33,S\n68,0,3,"Crease, Mr. Ernest James",male,19,0,0,S.P. 3464,8.1583,,S\n69,1,3,"Andersson, Miss. Erna Alexandra",female,17,4,2,3101281,7.925,,S\n70,0,3,"Kink, Mr. Vincenz",male,26,2,0,315151,8.6625,,S\n71,0,2,"Jenkin, Mr. Stephen Curnow",male,32,0,0,C.A. 33111,10.5,,S\n72,0,3,"Goodwin, Miss. Lillian Amy",female,16,5,2,CA 2144,46.9,,S\n73,0,2,"Hood, Mr. Ambrose Jr",male,21,0,0,S.O.C. 14879,73.5,,S\n74,0,3,"Chronopoulos, Mr. Apostolos",male,26,1,0,2680,14.4542,,C\n75,1,3,"Bing, Mr. Lee",male,32,0,0,1601,56.4958,,S\n76,0,3,"Moen, Mr. Sigurd Hansen",male,25,0,0,348123,7.65,F G73,S\n77,0,3,"Staneff, Mr. Ivan",male,,0,0,349208,7.8958,,S\n78,0,3,"Moutal, Mr. Rahamin Haim",male,,0,0,374746,8.05,,S\n79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29,,S\n80,1,3,"Dowdell, Miss. Elizabeth",female,30,0,0,364516,12.475,,S\n81,0,3,"Waelens, Mr. Achille",male,22,0,0,345767,9,,S\n82,1,3,"Sheerlinck, Mr. Jan Baptist",male,29,0,0,345779,9.5,,S\n83,1,3,"McDermott, Miss. Brigdet Delia",female,,0,0,330932,7.7875,,Q\n84,0,1,"Carrau, Mr. Francisco M",male,28,0,0,113059,47.1,,S\n85,1,2,"Ilett, Miss. Bertha",female,17,0,0,SO/C 14885,10.5,,S\n86,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)",female,33,3,0,3101278,15.85,,S\n87,0,3,"Ford, Mr. William Neal",male,16,1,3,W./C. 6608,34.375,,S\n88,0,3,"Slocovski, Mr. Selman Francis",male,,0,0,SOTON/OQ 392086,8.05,,S\n89,1,1,"Fortune, Miss. Mabel Helen",female,23,3,2,19950,263,C23 C25 C27,S\n90,0,3,"Celotti, Mr. Francesco",male,24,0,0,343275,8.05,,S\n91,0,3,"Christmann, Mr. Emil",male,29,0,0,343276,8.05,,S\n92,0,3,"Andreasson, Mr. Paul Edvin",male,20,0,0,347466,7.8542,,S\n93,0,1,"Chaffee, Mr. Herbert Fuller",male,46,1,0,W.E.P. 5734,61.175,E31,S\n94,0,3,"Dean, Mr. Bertram Frank",male,26,1,2,C.A. 2315,20.575,,S\n95,0,3,"Coxon, Mr. Daniel",male,59,0,0,364500,7.25,,S\n96,0,3,"Shorney, Mr. Charles Joseph",male,,0,0,374910,8.05,,S\n97,0,1,"Goldschmidt, Mr. George B",male,71,0,0,PC 17754,34.6542,A5,C\n98,1,1,"Greenfield, Mr. William Bertram",male,23,0,1,PC 17759,63.3583,D10 D12,C\n99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34,0,1,231919,23,,S\n100,0,2,"Kantor, Mr. Sinai",male,34,1,0,244367,26,,S\n101,0,3,"Petranec, Miss. Matilda",female,28,0,0,349245,7.8958,,S\n102,0,3,"Petroff, Mr. Pastcho (""Pentcho"")",male,,0,0,349215,7.8958,,S\n103,0,1,"White, Mr. Richard Frasar",male,21,0,1,35281,77.2875,D26,S\n104,0,3,"Johansson, Mr. Gustaf Joel",male,33,0,0,7540,8.6542,,S\n105,0,3,"Gustafsson, Mr. Anders Vilhelm",male,37,2,0,3101276,7.925,,S\n106,0,3,"Mionoff, Mr. Stoytcho",male,28,0,0,349207,7.8958,,S\n107,1,3,"Salkjelsvik, Miss. Anna Kristine",female,21,0,0,343120,7.65,,S\n108,1,3,"Moss, Mr. Albert Johan",male,,0,0,312991,7.775,,S\n109,0,3,"Rekic, Mr. Tido",male,38,0,0,349249,7.8958,,S\n110,1,3,"Moran, Miss. Bertha",female,,1,0,371110,24.15,,Q\n111,0,1,"Porter, Mr. Walter Chamberlain",male,47,0,0,110465,52,C110,S\n112,0,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,,C\n113,0,3,"Barton, Mr. David John",male,22,0,0,324669,8.05,,S\n114,0,3,"Jussila, Miss. Katriina",female,20,1,0,4136,9.825,,S\n115,0,3,"Attalah, Miss. Malake",female,17,0,0,2627,14.4583,,C\n116,0,3,"Pekoniemi, Mr. Edvard",male,21,0,0,STON/O 2. 3101294,7.925,,S\n117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.75,,Q\n118,0,2,"Turpin, Mr. William John Robert",male,29,1,0,11668,21,,S\n119,0,1,"Baxter, Mr. Quigg Edmond",male,24,0,1,PC 17558,247.5208,B58 B60,C\n120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2,4,2,347082,31.275,,S\n121,0,2,"Hickman, Mr. Stanley George",male,21,2,0,S.O.C. 14879,73.5,,S\n122,0,3,"Moore, Mr. Leonard Charles",male,,0,0,A4. 54510,8.05,,S\n123,0,2,"Nasser, Mr. Nicholas",male,32.5,1,0,237736,30.0708,,C\n124,1,2,"Webber, Miss. Susan",female,32.5,0,0,27267,13,E101,S\n125,0,1,"White, Mr. Percival Wayland",male,54,0,1,35281,77.2875,D26,S\n126,1,3,"Nicola-Yarred, Master. Elias",male,12,1,0,2651,11.2417,,C\n127,0,3,"McMahon, Mr. Martin",male,,0,0,370372,7.75,,Q\n128,1,3,"Madsen, Mr. Fridtjof Arne",male,24,0,0,C 17369,7.1417,,S\n129,1,3,"Peter, Miss. Anna",female,,1,1,2668,22.3583,F E69,C\n130,0,3,"Ekstrom, Mr. Johan",male,45,0,0,347061,6.975,,S\n131,0,3,"Drazenoic, Mr. Jozef",male,33,0,0,349241,7.8958,,C\n132,0,3,"Coelho, Mr. Domingos Fernandeo",male,20,0,0,SOTON/O.Q. 3101307,7.05,,S\n133,0,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47,1,0,A/5. 3337,14.5,,S\n134,1,2,"Weisz, Mrs. Leopold (Mathilde Francoise Pede)",female,29,1,0,228414,26,,S\n135,0,2,"Sobey, Mr. Samuel James Hayden",male,25,0,0,C.A. 29178,13,,S\n136,0,2,"Richard, Mr. Emile",male,23,0,0,SC/PARIS 2133,15.0458,,C\n137,1,1,"Newsom, Miss. Helen Monypeny",female,19,0,2,11752,26.2833,D47,S\n138,0,1,"Futrelle, Mr. Jacques Heath",male,37,1,0,113803,53.1,C123,S\n139,0,3,"Osen, Mr. Olaf Elon",male,16,0,0,7534,9.2167,,S\n140,0,1,"Giglio, Mr. Victor",male,24,0,0,PC 17593,79.2,B86,C\n141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,,0,2,2678,15.2458,,C\n142,1,3,"Nysten, Miss. Anna Sofia",female,22,0,0,347081,7.75,,S\n143,1,3,"Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)",female,24,1,0,STON/O2. 3101279,15.85,,S\n144,0,3,"Burke, Mr. Jeremiah",male,19,0,0,365222,6.75,,Q\n145,0,2,"Andrew, Mr. Edgardo Samuel",male,18,0,0,231945,11.5,,S\n146,0,2,"Nicholls, Mr. Joseph Charles",male,19,1,1,C.A. 33112,36.75,,S\n147,1,3,"Andersson, Mr. August Edvard (""Wennerstrom"")",male,27,0,0,350043,7.7958,,S\n148,0,3,"Ford, Miss. Robina Maggie ""Ruby""",female,9,2,2,W./C. 6608,34.375,,S\n149,0,2,"Navratil, Mr. Michel (""Louis M Hoffman"")",male,36.5,0,2,230080,26,F2,S\n150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42,0,0,244310,13,,S\n151,0,2,"Bateman, Rev. Robert James",male,51,0,0,S.O.P. 1166,12.525,,S\n152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22,1,0,113776,66.6,C2,S\n153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.05,,S\n154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5,,S\n155,0,3,"Olsen, Mr. Ole Martin",male,,0,0,Fa 265302,7.3125,,S\n156,0,1,"Williams, Mr. Charles Duane",male,51,0,1,PC 17597,61.3792,,C\n157,1,3,"Gilnagh, Miss. Katherine ""Katie""",female,16,0,0,35851,7.7333,,Q\n158,0,3,"Corn, Mr. Harry",male,30,0,0,SOTON/OQ 392090,8.05,,S\n159,0,3,"Smiljanic, Mr. Mile",male,,0,0,315037,8.6625,,S\n160,0,3,"Sage, Master. Thomas Henry",male,,8,2,CA. 2343,69.55,,S\n161,0,3,"Cribb, Mr. John Hatfield",male,44,0,1,371362,16.1,,S\n162,1,2,"Watt, Mrs. James (Elizabeth ""Bessie"" Inglis Milne)",female,40,0,0,C.A. 33595,15.75,,S\n163,0,3,"Bengtsson, Mr. John Viktor",male,26,0,0,347068,7.775,,S\n164,0,3,"Calic, Mr. Jovo",male,17,0,0,315093,8.6625,,S\n165,0,3,"Panula, Master. Eino Viljami",male,1,4,1,3101295,39.6875,,S\n166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9,0,2,363291,20.525,,S\n167,1,1,"Chibnall, Mrs. (Edith Martha Bowerman)",female,,0,1,113505,55,E33,S\n168,0,3,"Skoog, Mrs. William (Anna Bernhardina Karlsson)",female,45,1,4,347088,27.9,,S\n169,0,1,"Baumann, Mr. John D",male,,0,0,PC 17318,25.925,,S\n170,0,3,"Ling, Mr. Lee",male,28,0,0,1601,56.4958,,S\n171,0,1,"Van der hoef, Mr. Wyckoff",male,61,0,0,111240,33.5,B19,S\n172,0,3,"Rice, Master. Arthur",male,4,4,1,382652,29.125,,Q\n173,1,3,"Johnson, Miss. Eleanor Ileen",female,1,1,1,347742,11.1333,,S\n174,0,3,"Sivola, Mr. Antti Wilhelm",male,21,0,0,STON/O 2. 3101280,7.925,,S\n175,0,1,"Smith, Mr. James Clinch",male,56,0,0,17764,30.6958,A7,C\n176,0,3,"Klasen, Mr. Klas Albin",male,18,1,1,350404,7.8542,,S\n177,0,3,"Lefebre, Master. Henry Forbes",male,,3,1,4133,25.4667,,S\n178,0,1,"Isham, Miss. Ann Elizabeth",female,50,0,0,PC 17595,28.7125,C49,C\n179,0,2,"Hale, Mr. Reginald",male,30,0,0,250653,13,,S\n180,0,3,"Leonard, Mr. Lionel",male,36,0,0,LINE,0,,S\n181,0,3,"Sage, Miss. Constance Gladys",female,,8,2,CA. 2343,69.55,,S\n182,0,2,"Pernot, Mr. Rene",male,,0,0,SC/PARIS 2131,15.05,,C\n183,0,3,"Asplund, Master. Clarence Gustaf Hugo",male,9,4,2,347077,31.3875,,S\n184,1,2,"Becker, Master. Richard F",male,1,2,1,230136,39,F4,S\n185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4,0,2,315153,22.025,,S\n186,0,1,"Rood, Mr. Hugh Roscoe",male,,0,0,113767,50,A32,S\n187,1,3,"O\'Brien, Mrs. Thomas (Johanna ""Hannah"" Godfrey)",female,,1,0,370365,15.5,,Q\n188,1,1,"Romaine, Mr. Charles Hallace (""Mr C Rolmane"")",male,45,0,0,111428,26.55,,S\n189,0,3,"Bourke, Mr. John",male,40,1,1,364849,15.5,,Q\n190,0,3,"Turcin, Mr. Stjepan",male,36,0,0,349247,7.8958,,S\n191,1,2,"Pinsky, Mrs. (Rosa)",female,32,0,0,234604,13,,S\n192,0,2,"Carbines, Mr. William",male,19,0,0,28424,13,,S\n193,1,3,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19,1,0,350046,7.8542,,S\n194,1,2,"Navratil, Master. Michel M",male,3,1,1,230080,26,F2,S\n195,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44,0,0,PC 17610,27.7208,B4,C\n196,1,1,"Lurette, Miss. Elise",female,58,0,0,PC 17569,146.5208,B80,C\n197,0,3,"Mernagh, Mr. Robert",male,,0,0,368703,7.75,,Q\n198,0,3,"Olsen, Mr. Karl Siegwart Andreas",male,42,0,1,4579,8.4042,,S\n199,1,3,"Madigan, Miss. Margaret ""Maggie""",female,,0,0,370370,7.75,,Q\n200,0,2,"Yrois, Miss. Henriette (""Mrs Harbeck"")",female,24,0,0,248747,13,,S\n201,0,3,"Vande Walle, Mr. Nestor Cyriel",male,28,0,0,345770,9.5,,S\n202,0,3,"Sage, Mr. Frederick",male,,8,2,CA. 2343,69.55,,S\n203,0,3,"Johanson, Mr. Jakob Alfred",male,34,0,0,3101264,6.4958,,S\n204,0,3,"Youseff, Mr. Gerious",male,45.5,0,0,2628,7.225,,C\n205,1,3,"Cohen, Mr. Gurshon ""Gus""",male,18,0,0,A/5 3540,8.05,,S\n206,0,3,"Strom, Miss. Telma Matilda",female,2,0,1,347054,10.4625,G6,S\n207,0,3,"Backstrom, Mr. Karl Alfred",male,32,1,0,3101278,15.85,,S\n208,1,3,"Albimona, Mr. Nassef Cassem",male,26,0,0,2699,18.7875,,C\n209,1,3,"Carr, Miss. Helen ""Ellen""",female,16,0,0,367231,7.75,,Q\n210,1,1,"Blank, Mr. Henry",male,40,0,0,112277,31,A31,C\n211,0,3,"Ali, Mr. Ahmed",male,24,0,0,SOTON/O.Q. 3101311,7.05,,S\n212,1,2,"Cameron, Miss. Clear Annie",female,35,0,0,F.C.C. 13528,21,,S\n213,0,3,"Perkin, Mr. John Henry",male,22,0,0,A/5 21174,7.25,,S\n214,0,2,"Givard, Mr. Hans Kristensen",male,30,0,0,250646,13,,S\n215,0,3,"Kiernan, Mr. Philip",male,,1,0,367229,7.75,,Q\n216,1,1,"Newell, Miss. Madeleine",female,31,1,0,35273,113.275,D36,C\n217,1,3,"Honkanen, Miss. Eliina",female,27,0,0,STON/O2. 3101283,7.925,,S\n218,0,2,"Jacobsohn, Mr. Sidney Samuel",male,42,1,0,243847,27,,S\n219,1,1,"Bazzani, Miss. Albina",female,32,0,0,11813,76.2917,D15,C\n220,0,2,"Harris, Mr. Walter",male,30,0,0,W/C 14208,10.5,,S\n221,1,3,"Sunderland, Mr. Victor Francis",male,16,0,0,SOTON/OQ 392089,8.05,,S\n222,0,2,"Bracken, Mr. James H",male,27,0,0,220367,13,,S\n223,0,3,"Green, Mr. George Henry",male,51,0,0,21440,8.05,,S\n224,0,3,"Nenkoff, Mr. Christo",male,,0,0,349234,7.8958,,S\n225,1,1,"Hoyt, Mr. Frederick Maxfield",male,38,1,0,19943,90,C93,S\n226,0,3,"Berglund, Mr. Karl Ivar Sven",male,22,0,0,PP 4348,9.35,,S\n227,1,2,"Mellors, Mr. William John",male,19,0,0,SW/PP 751,10.5,,S\n228,0,3,"Lovell, Mr. John Hall (""Henry"")",male,20.5,0,0,A/5 21173,7.25,,S\n229,0,2,"Fahlstrom, Mr. Arne Jonas",male,18,0,0,236171,13,,S\n230,0,3,"Lefebre, Miss. Mathilde",female,,3,1,4133,25.4667,,S\n231,1,1,"Harris, Mrs. Henry Birkhardt (Irene Wallach)",female,35,1,0,36973,83.475,C83,S\n232,0,3,"Larsson, Mr. Bengt Edvin",male,29,0,0,347067,7.775,,S\n233,0,2,"Sjostedt, Mr. Ernst Adolf",male,59,0,0,237442,13.5,,S\n234,1,3,"Asplund, Miss. Lillian Gertrud",female,5,4,2,347077,31.3875,,S\n235,0,2,"Leyson, Mr. Robert William Norman",male,24,0,0,C.A. 29566,10.5,,S\n236,0,3,"Harknett, Miss. Alice Phoebe",female,,0,0,W./C. 6609,7.55,,S\n237,0,2,"Hold, Mr. Stephen",male,44,1,0,26707,26,,S\n238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8,0,2,C.A. 31921,26.25,,S\n239,0,2,"Pengelly, Mr. Frederick William",male,19,0,0,28665,10.5,,S\n240,0,2,"Hunt, Mr. George Henry",male,33,0,0,SCO/W 1585,12.275,,S\n241,0,3,"Zabour, Miss. Thamine",female,,1,0,2665,14.4542,,C\n242,1,3,"Murphy, Miss. Katherine ""Kate""",female,,1,0,367230,15.5,,Q\n243,0,2,"Coleridge, Mr. Reginald Charles",male,29,0,0,W./C. 14263,10.5,,S\n244,0,3,"Maenpaa, Mr. Matti Alexanteri",male,22,0,0,STON/O 2. 3101275,7.125,,S\n245,0,3,"Attalah, Mr. Sleiman",male,30,0,0,2694,7.225,,C\n246,0,1,"Minahan, Dr. William Edward",male,44,2,0,19928,90,C78,Q\n247,0,3,"Lindahl, Miss. Agda Thorilda Viktoria",female,25,0,0,347071,7.775,,S\n248,1,2,"Hamalainen, Mrs. William (Anna)",female,24,0,2,250649,14.5,,S\n249,1,1,"Beckwith, Mr. Richard Leonard",male,37,1,1,11751,52.5542,D35,S\n250,0,2,"Carter, Rev. Ernest Courtenay",male,54,1,0,244252,26,,S\n251,0,3,"Reed, Mr. James George",male,,0,0,362316,7.25,,S\n252,0,3,"Strom, Mrs. Wilhelm (Elna Matilda Persson)",female,29,1,1,347054,10.4625,G6,S\n253,0,1,"Stead, Mr. William Thomas",male,62,0,0,113514,26.55,C87,S\n254,0,3,"Lobb, Mr. William Arthur",male,30,1,0,A/5. 3336,16.1,,S\n255,0,3,"Rosblom, Mrs. Viktor (Helena Wilhelmina)",female,41,0,2,370129,20.2125,,S\n256,1,3,"Touma, Mrs. Darwis (Hanne Youssef Razi)",female,29,0,2,2650,15.2458,,C\n257,1,1,"Thorne, Mrs. Gertrude Maybelle",female,,0,0,PC 17585,79.2,,C\n258,1,1,"Cherry, Miss. Gladys",female,30,0,0,110152,86.5,B77,S\n259,1,1,"Ward, Miss. Anna",female,35,0,0,PC 17755,512.3292,,C\n260,1,2,"Parrish, Mrs. (Lutie Davis)",female,50,0,1,230433,26,,S\n261,0,3,"Smith, Mr. Thomas",male,,0,0,384461,7.75,,Q\n262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3,4,2,347077,31.3875,,S\n263,0,1,"Taussig, Mr. Emil",male,52,1,1,110413,79.65,E67,S\n264,0,1,"Harrison, Mr. William",male,40,0,0,112059,0,B94,S\n265,0,3,"Henry, Miss. Delia",female,,0,0,382649,7.75,,Q\n266,0,2,"Reeves, Mr. David",male,36,0,0,C.A. 17248,10.5,,S\n267,0,3,"Panula, Mr. Ernesti Arvid",male,16,4,1,3101295,39.6875,,S\n268,1,3,"Persson, Mr. Ernst Ulrik",male,25,1,0,347083,7.775,,S\n269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58,0,1,PC 17582,153.4625,C125,S\n270,1,1,"Bissette, Miss. Amelia",female,35,0,0,PC 17760,135.6333,C99,S\n271,0,1,"Cairns, Mr. Alexander",male,,0,0,113798,31,,S\n272,1,3,"Tornquist, Mr. William Henry",male,25,0,0,LINE,0,,S\n273,1,2,"Mellinger, Mrs. (Elizabeth Anne Maidment)",female,41,0,1,250644,19.5,,S\n274,0,1,"Natsch, Mr. Charles H",male,37,0,1,PC 17596,29.7,C118,C\n275,1,3,"Healy, Miss. Hanora ""Nora""",female,,0,0,370375,7.75,,Q\n276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63,1,0,13502,77.9583,D7,S\n277,0,3,"Lindblom, Miss. Augusta Charlotta",female,45,0,0,347073,7.75,,S\n278,0,2,"Parkes, Mr. Francis ""Frank""",male,,0,0,239853,0,,S\n279,0,3,"Rice, Master. Eric",male,7,4,1,382652,29.125,,Q\n280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35,1,1,C.A. 2673,20.25,,S\n281,0,3,"Duane, Mr. Frank",male,65,0,0,336439,7.75,,Q\n282,0,3,"Olsson, Mr. Nils Johan Goransson",male,28,0,0,347464,7.8542,,S\n283,0,3,"de Pelsmaeker, Mr. Alfons",male,16,0,0,345778,9.5,,S\n284,1,3,"Dorking, Mr. Edward Arthur",male,19,0,0,A/5. 10482,8.05,,S\n285,0,1,"Smith, Mr. Richard William",male,,0,0,113056,26,A19,S\n286,0,3,"Stankovic, Mr. Ivan",male,33,0,0,349239,8.6625,,C\n287,1,3,"de Mulder, Mr. Theodore",male,30,0,0,345774,9.5,,S\n288,0,3,"Naidenoff, Mr. Penko",male,22,0,0,349206,7.8958,,S\n289,1,2,"Hosono, Mr. Masabumi",male,42,0,0,237798,13,,S\n290,1,3,"Connolly, Miss. Kate",female,22,0,0,370373,7.75,,Q\n291,1,1,"Barber, Miss. Ellen ""Nellie""",female,26,0,0,19877,78.85,,S\n292,1,1,"Bishop, Mrs. D

Wczytanie danych

In [ ]:
data = session.read.csv('titanic.csv') # reading the dataset through the given path
data

DataFrame[_c0: string, _c1: string, _c2: string, _c3: string, _c4: string, _c5: string, _c6: string, _c7: string, _c8: string, _c9: string, _c10: string, _c11: string]

In [ ]:
data.show()

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
|        _c0|     _c1|   _c2|                 _c3|   _c4| _c5|  _c6|  _c7|             _c8|    _c9| _c10|    _c11|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
|PassengerId|Survived|Pclass|                Name|   Sex| Age|SibSp|Parch|          Ticket|   Fare|Cabin|Embarked|
|          1|       0|     3|Braund, Mr. Owen ...|  male|  22|    1|    0|       A/5 21171|   7.25| null|       S|
|          2|       1|     1|Cumings, Mrs. Joh...|female|  38|    1|    0|        PC 17599|71.2833|  C85|       C|
|          3|       1|     3|Heikkinen, Miss. ...|female|  26|    0|    0|STON/O2. 3101282|  7.925| null|       S|
|          4|       1|     1|Futrelle, Mrs. Ja...|female|  35|    1|    0|          113803|   53.1| C123|       S|
|          5|       0|     3|Allen, Mr. Willia...|  male|  35|    0|    0|          373450|   8.05| null|       S|
|          6|       0|     3|    Moran, Mr. James|  male|null|    0|    0|          330877| 8.4583| null|       Q|
|          7|       0|     1|McCarthy, Mr. Tim...|  male|  54|    0|    0|           17463|51.8625|  E46|       S|
|          8|       0|     3|Palsson, Master. ...|  male|   2|    3|    1|          349909| 21.075| null|       S|
|          9|       1|     3|Johnson, Mrs. Osc...|female|  27|    0|    2|          347742|11.1333| null|       S|
|         10|       1|     2|Nasser, Mrs. Nich...|female|  14|    1|    0|          237736|30.0708| null|       C|
|         11|       1|     3|Sandstrom, Miss. ...|female|   4|    1|    1|         PP 9549|   16.7|   G6|       S|
|         12|       1|     1|Bonnell, Miss. El...|female|  58|    0|    0|          113783|  26.55| C103|       S|
|         13|       0|     3|Saundercock, Mr. ...|  male|  20|    0|    0|       A/5. 2151|   8.05| null|       S|
|         14|       0|     3|Andersson, Mr. An...|  male|  39|    1|    5|          347082| 31.275| null|       S|
|         15|       0|     3|Vestrom, Miss. Hu...|female|  14|    0|    0|          350406| 7.8542| null|       S|
|         16|       1|     2|Hewlett, Mrs. (Ma...|female|  55|    0|    0|          248706|     16| null|       S|
|         17|       0|     3|Rice, Master. Eugene|  male|   2|    4|    1|          382652| 29.125| null|       Q|
|         18|       1|     2|Williams, Mr. Cha...|  male|null|    0|    0|          244373|     13| null|       S|
|         19|       0|     3|Vander Planke, Mr...|female|  31|    1|    0|          345763|     18| null|       S|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
only showing top 20 rows

In [ ]:
data = session.read.option('header', 'true').csv('titanic.csv')

In [ ]:
data.show()

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
|PassengerId|Survived|Pclass|                Name|   Sex| Age|SibSp|Parch|          Ticket|   Fare|Cabin|Embarked|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
|          1|       0|     3|Braund, Mr. Owen ...|  male|  22|    1|    0|       A/5 21171|   7.25| null|       S|
|          2|       1|     1|Cumings, Mrs. Joh...|female|  38|    1|    0|        PC 17599|71.2833|  C85|       C|
|          3|       1|     3|Heikkinen, Miss. ...|female|  26|    0|    0|STON/O2. 3101282|  7.925| null|       S|
|          4|       1|     1|Futrelle, Mrs. Ja...|female|  35|    1|    0|          113803|   53.1| C123|       S|
|          5|       0|     3|Allen, Mr. Willia...|  male|  35|    0|    0|          373450|   8.05| null|       S|
|          6|       0|     3|    Moran, Mr. James|  male|null|    0|    0|          330877| 8.4583| null|       Q|
|          7|       0|     1|McCarthy, Mr. Tim...|  male|  54|    0|    0|           17463|51.8625|  E46|       S|
|          8|       0|     3|Palsson, Master. ...|  male|   2|    3|    1|          349909| 21.075| null|       S|
|          9|       1|     3|Johnson, Mrs. Osc...|female|  27|    0|    2|          347742|11.1333| null|       S|
|         10|       1|     2|Nasser, Mrs. Nich...|female|  14|    1|    0|          237736|30.0708| null|       C|
|         11|       1|     3|Sandstrom, Miss. ...|female|   4|    1|    1|         PP 9549|   16.7|   G6|       S|
|         12|       1|     1|Bonnell, Miss. El...|female|  58|    0|    0|          113783|  26.55| C103|       S|
|         13|       0|     3|Saundercock, Mr. ...|  male|  20|    0|    0|       A/5. 2151|   8.05| null|       S|
|         14|       0|     3|Andersson, Mr. An...|  male|  39|    1|    5|          347082| 31.275| null|       S|
|         15|       0|     3|Vestrom, Miss. Hu...|female|  14|    0|    0|          350406| 7.8542| null|       S|
|         16|       1|     2|Hewlett, Mrs. (Ma...|female|  55|    0|    0|          248706|     16| null|       S|
|         17|       0|     3|Rice, Master. Eugene|  male|   2|    4|    1|          382652| 29.125| null|       Q|
|         18|       1|     2|Williams, Mr. Cha...|  male|null|    0|    0|          244373|     13| null|       S|
|         19|       0|     3|Vander Planke, Mr...|female|  31|    1|    0|          345763|     18| null|       S|
|         20|       1|     3|Masselmani, Mrs. ...|female|null|    0|    0|            2649|  7.225| null|       C|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
only showing top 20 rows

In [ ]:
data.printSchema()

root
 |-- PassengerId: string (nullable = true)
 |-- Survived: string (nullable = true)
 |-- Pclass: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Sex: string (nullable = true)
 |-- Age: string (nullable = true)
 |-- SibSp: string (nullable = true)
 |-- Parch: string (nullable = true)
 |-- Ticket: string (nullable = true)
 |-- Fare: string (nullable = true)
 |-- Cabin: string (nullable = true)
 |-- Embarked: string (nullable = true)

In [ ]:
data = session.read.csv('titanic.csv',inferSchema=True, header =True)

data.printSchema()

root
 |-- PassengerId: integer (nullable = true)
 |-- Survived: integer (nullable = true)
 |-- Pclass: integer (nullable = true)
 |-- Name: string (nullable = true)
 |-- Sex: string (nullable = true)
 |-- Age: double (nullable = true)
 |-- SibSp: integer (nullable = true)
 |-- Parch: integer (nullable = true)
 |-- Ticket: string (nullable = true)
 |-- Fare: double (nullable = true)
 |-- Cabin: string (nullable = true)
 |-- Embarked: string (nullable = true)

### Przykład tworzenia Dataframe Pyspark z Dataframe Pandas

In [ ]:
from datetime import datetime, date

pandas_df = pd.DataFrame({
    'a': [1, 2, 3],
    'b': [2., 3., 4.],
    'c': ['string1', 'string2', 'string3'],
    'd': [date(2000, 1, 1), date(2000, 2, 1), date(2000, 3, 1)],
    'e': [datetime(2000, 1, 1, 12, 0), datetime(2000, 1, 2, 12, 0), datetime(2000, 1, 3, 12, 0)]
})
df = session.createDataFrame(pandas_df)
df.show()

/content/spark-3.0.0-bin-hadoop3.2/python/pyspark/sql/pandas/conversion.py:327: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for column, series in pdf.iteritems():

+---+---+-------+----------+-------------------+
|  a|  b|      c|         d|                  e|
+---+---+-------+----------+-------------------+
|  1|2.0|string1|2000-01-01|2000-01-01 12:00:00|
|  2|3.0|string2|2000-02-01|2000-01-02 12:00:00|
|  3|4.0|string3|2000-03-01|2000-01-03 12:00:00|
+---+---+-------+----------+-------------------+

Dane mogą być również wyświetlane w sposób wertykalny

In [ ]:
df.show(1, vertical=True)

-RECORD 0------------------
 a   | 1
 b   | 2.0
 c   | string1
 d   | 2000-01-01
 e   | 2000-01-01 12:00:00
only showing top 1 row

Zapytania do bazy o wartości statystyczne

1.•	Obliczyć ile osób przeżyło

In [ ]:
data.filter(data['Survived'] == 1).count()

342

•	Obliczyć procent osób które przeżyły

In [ ]:
data.filter(data['Survived'] == 1).count() / data.count() * 100

38.38383838383838

•	Obliczyć średni wiek pasażerów

In [ ]:
a = data.agg({"Age": 'avg'})
a.show()

+-----------------+
|         avg(Age)|
+-----------------+
|29.69911764705882|
+-----------------+

•	Obliczyć procentowo i liczbowo ilość pasażerów korzystających z różnych klas podróży (Pclass)

In [ ]:
data_all = data.count()
grouped_data = data.groupBy("Pclass").count()
grouped_data.show()

grouped_data.withColumn('pclass %', grouped_data['count'] / data_all * 100).show()

+------+-----+
|Pclass|count|
+------+-----+
|     1|  216|
|     3|  491|
|     2|  184|
+------+-----+

+------+-----+------------------+
|Pclass|count|          pclass %|
+------+-----+------------------+
|     1|  216|24.242424242424242|
|     3|  491|55.106621773288445|
|     2|  184| 20.65095398428732|
+------+-----+------------------+

Czy więcej było kobiet czy mężczyzn na statku

In [ ]:
data_sex = data.groupBy("Sex").count()
data_sex.show()

+------+-----+
|   Sex|count|
+------+-----+
|female|  314|
|  male|  577|
+------+-----+

Mediana i odchylenie standardowe

In [ ]:
import numpy as np
my_list = data.select(collect_list('Fare')).first()[0]

In [ ]:
np.median(my_list)

14.4542

In [ ]:
np.std(my_list)

49.6655344447741

In [ ]:
a = data.agg({"Fare": 'std'})
a.show()

+-----------------+
|     stddev(Fare)|
+-----------------+
|49.69342859718089|
+-----------------+

Ile osób najwięcej znajdowało się w jednej kabinie

In [ ]:
grouped_cabin = data.groupBy("Cabin").count()
grouped_cabin.sort('count', ascending=False).show()

+-----------+-----+
|      Cabin|count|
+-----------+-----+
|       null|  687|
|C23 C25 C27|    4|
|         G6|    4|
|    B96 B98|    4|
|          D|    3|
|       E101|    3|
|    C22 C26|    3|
|         F2|    3|
|        F33|    3|
|        E33|    2|
|    B58 B60|    2|
|       C126|    2|
|        C65|    2|
|         E8|    2|
|        B22|    2|
|        D35|    2|
|        E44|    2|
|        D20|    2|
|        C78|    2|
|       C123|    2|
+-----------+-----+
only showing top 20 rows

Wybór kolumn

In [ ]:
data.select('PassengerId').show(10)

+-----------+
|PassengerId|
+-----------+
|          1|
|          2|
|          3|
|          4|
|          5|
|          6|
|          7|
|          8|
|          9|
|         10|
+-----------+
only showing top 10 rows

In [ ]:
data.select('Name', 'Age').show(10)

+--------------------+----+
|                Name| Age|
+--------------------+----+
|Braund, Mr. Owen ...|22.0|
|Cumings, Mrs. Joh...|38.0|
|Heikkinen, Miss. ...|26.0|
|Futrelle, Mrs. Ja...|35.0|
|Allen, Mr. Willia...|35.0|
|    Moran, Mr. James|null|
|McCarthy, Mr. Tim...|54.0|
|Palsson, Master. ...| 2.0|
|Johnson, Mrs. Osc...|27.0|
|Nasser, Mrs. Nich...|14.0|
+--------------------+----+
only showing top 10 rows

Dodawanie nowej kolumny

In [ ]:
# adding columns in dataframe
data = data.withColumn('Age_after_3_y', data['Age']+3)
data.show(10)

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+-------------+
|PassengerId|Survived|Pclass|                Name|   Sex| Age|SibSp|Parch|          Ticket|   Fare|Cabin|Embarked|Age_after_3_y|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+-------------+
|          1|       0|     3|Braund, Mr. Owen ...|  male|22.0|    1|    0|       A/5 21171|   7.25| null|       S|         25.0|
|          2|       1|     1|Cumings, Mrs. Joh...|female|38.0|    1|    0|        PC 17599|71.2833|  C85|       C|         41.0|
|          3|       1|     3|Heikkinen, Miss. ...|female|26.0|    0|    0|STON/O2. 3101282|  7.925| null|       S|         29.0|
|          4|       1|     1|Futrelle, Mrs. Ja...|female|35.0|    1|    0|          113803|   53.1| C123|       S|         38.0|
|          5|       0|     3|Allen, Mr. Willia...|  male|35.0|    0|    0|          373450|   8.05| null|       S|         38.0|
|          6|       0|     3|    Moran, Mr. James|  male|null|    0|    0|          330877| 8.4583| null|       Q|         null|
|          7|       0|     1|McCarthy, Mr. Tim...|  male|54.0|    0|    0|           17463|51.8625|  E46|       S|         57.0|
|          8|       0|     3|Palsson, Master. ...|  male| 2.0|    3|    1|          349909| 21.075| null|       S|          5.0|
|          9|       1|     3|Johnson, Mrs. Osc...|female|27.0|    0|    2|          347742|11.1333| null|       S|         30.0|
|         10|       1|     2|Nasser, Mrs. Nich...|female|14.0|    1|    0|          237736|30.0708| null|       C|         17.0|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+-------------+
only showing top 10 rows

In [ ]:
data.printSchema()

root
 |-- PassengerId: integer (nullable = true)
 |-- Survived: integer (nullable = true)
 |-- Pclass: integer (nullable = true)
 |-- Name: string (nullable = true)
 |-- Sex: string (nullable = true)
 |-- Age: double (nullable = true)
 |-- SibSp: integer (nullable = true)
 |-- Parch: integer (nullable = true)
 |-- Ticket: string (nullable = true)
 |-- Fare: double (nullable = true)
 |-- Cabin: string (nullable = true)
 |-- Embarked: string (nullable = true)
 |-- Age_after_3_y: double (nullable = true)

Usuwanie kolumn

In [ ]:
# dropping the columns
data = data.drop('Age_after_3_y')
data.show()

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
|PassengerId|Survived|Pclass|                Name|   Sex| Age|SibSp|Parch|          Ticket|   Fare|Cabin|Embarked|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
|          1|       0|     3|Braund, Mr. Owen ...|  male|22.0|    1|    0|       A/5 21171|   7.25| null|       S|
|          2|       1|     1|Cumings, Mrs. Joh...|female|38.0|    1|    0|        PC 17599|71.2833|  C85|       C|
|          3|       1|     3|Heikkinen, Miss. ...|female|26.0|    0|    0|STON/O2. 3101282|  7.925| null|       S|
|          4|       1|     1|Futrelle, Mrs. Ja...|female|35.0|    1|    0|          113803|   53.1| C123|       S|
|          5|       0|     3|Allen, Mr. Willia...|  male|35.0|    0|    0|          373450|   8.05| null|       S|
|          6|       0|     3|    Moran, Mr. James|  male|null|    0|    0|          330877| 8.4583| null|       Q|
|          7|       0|     1|McCarthy, Mr. Tim...|  male|54.0|    0|    0|           17463|51.8625|  E46|       S|
|          8|       0|     3|Palsson, Master. ...|  male| 2.0|    3|    1|          349909| 21.075| null|       S|
|          9|       1|     3|Johnson, Mrs. Osc...|female|27.0|    0|    2|          347742|11.1333| null|       S|
|         10|       1|     2|Nasser, Mrs. Nich...|female|14.0|    1|    0|          237736|30.0708| null|       C|
|         11|       1|     3|Sandstrom, Miss. ...|female| 4.0|    1|    1|         PP 9549|   16.7|   G6|       S|
|         12|       1|     1|Bonnell, Miss. El...|female|58.0|    0|    0|          113783|  26.55| C103|       S|
|         13|       0|     3|Saundercock, Mr. ...|  male|20.0|    0|    0|       A/5. 2151|   8.05| null|       S|
|         14|       0|     3|Andersson, Mr. An...|  male|39.0|    1|    5|          347082| 31.275| null|       S|
|         15|       0|     3|Vestrom, Miss. Hu...|female|14.0|    0|    0|          350406| 7.8542| null|       S|
|         16|       1|     2|Hewlett, Mrs. (Ma...|female|55.0|    0|    0|          248706|   16.0| null|       S|
|         17|       0|     3|Rice, Master. Eugene|  male| 2.0|    4|    1|          382652| 29.125| null|       Q|
|         18|       1|     2|Williams, Mr. Cha...|  male|null|    0|    0|          244373|   13.0| null|       S|
|         19|       0|     3|Vander Planke, Mr...|female|31.0|    1|    0|          345763|   18.0| null|       S|
|         20|       1|     3|Masselmani, Mrs. ...|female|null|    0|    0|            2649|  7.225| null|       C|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
only showing top 20 rows

Zmiana nazwy kolumn

In [ ]:
# renaming the columns
data = data.withColumnRenamed('Fare', 'Price')
data.show()

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
|PassengerId|Survived|Pclass|                Name|   Sex| Age|SibSp|Parch|          Ticket|  Price|Cabin|Embarked|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
|          1|       0|     3|Braund, Mr. Owen ...|  male|22.0|    1|    0|       A/5 21171|   7.25| null|       S|
|          2|       1|     1|Cumings, Mrs. Joh...|female|38.0|    1|    0|        PC 17599|71.2833|  C85|       C|
|          3|       1|     3|Heikkinen, Miss. ...|female|26.0|    0|    0|STON/O2. 3101282|  7.925| null|       S|
|          4|       1|     1|Futrelle, Mrs. Ja...|female|35.0|    1|    0|          113803|   53.1| C123|       S|
|          5|       0|     3|Allen, Mr. Willia...|  male|35.0|    0|    0|          373450|   8.05| null|       S|
|          6|       0|     3|    Moran, Mr. James|  male|null|    0|    0|          330877| 8.4583| null|       Q|
|          7|       0|     1|McCarthy, Mr. Tim...|  male|54.0|    0|    0|           17463|51.8625|  E46|       S|
|          8|       0|     3|Palsson, Master. ...|  male| 2.0|    3|    1|          349909| 21.075| null|       S|
|          9|       1|     3|Johnson, Mrs. Osc...|female|27.0|    0|    2|          347742|11.1333| null|       S|
|         10|       1|     2|Nasser, Mrs. Nich...|female|14.0|    1|    0|          237736|30.0708| null|       C|
|         11|       1|     3|Sandstrom, Miss. ...|female| 4.0|    1|    1|         PP 9549|   16.7|   G6|       S|
|         12|       1|     1|Bonnell, Miss. El...|female|58.0|    0|    0|          113783|  26.55| C103|       S|
|         13|       0|     3|Saundercock, Mr. ...|  male|20.0|    0|    0|       A/5. 2151|   8.05| null|       S|
|         14|       0|     3|Andersson, Mr. An...|  male|39.0|    1|    5|          347082| 31.275| null|       S|
|         15|       0|     3|Vestrom, Miss. Hu...|female|14.0|    0|    0|          350406| 7.8542| null|       S|
|         16|       1|     2|Hewlett, Mrs. (Ma...|female|55.0|    0|    0|          248706|   16.0| null|       S|
|         17|       0|     3|Rice, Master. Eugene|  male| 2.0|    4|    1|          382652| 29.125| null|       Q|
|         18|       1|     2|Williams, Mr. Cha...|  male|null|    0|    0|          244373|   13.0| null|       S|
|         19|       0|     3|Vander Planke, Mr...|female|31.0|    1|    0|          345763|   18.0| null|       S|
|         20|       1|     3|Masselmani, Mrs. ...|female|null|    0|    0|            2649|  7.225| null|       C|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
only showing top 20 rows

Usuwanie pustych wierszy

In [ ]:
data = data.na.drop(how = 'any', thresh = 2)
data.show()

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
|PassengerId|Survived|Pclass|                Name|   Sex| Age|SibSp|Parch|          Ticket|  Price|Cabin|Embarked|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
|          1|       0|     3|Braund, Mr. Owen ...|  male|22.0|    1|    0|       A/5 21171|   7.25| null|       S|
|          2|       1|     1|Cumings, Mrs. Joh...|female|38.0|    1|    0|        PC 17599|71.2833|  C85|       C|
|          3|       1|     3|Heikkinen, Miss. ...|female|26.0|    0|    0|STON/O2. 3101282|  7.925| null|       S|
|          4|       1|     1|Futrelle, Mrs. Ja...|female|35.0|    1|    0|          113803|   53.1| C123|       S|
|          5|       0|     3|Allen, Mr. Willia...|  male|35.0|    0|    0|          373450|   8.05| null|       S|
|          6|       0|     3|    Moran, Mr. James|  male|null|    0|    0|          330877| 8.4583| null|       Q|
|          7|       0|     1|McCarthy, Mr. Tim...|  male|54.0|    0|    0|           17463|51.8625|  E46|       S|
|          8|       0|     3|Palsson, Master. ...|  male| 2.0|    3|    1|          349909| 21.075| null|       S|
|          9|       1|     3|Johnson, Mrs. Osc...|female|27.0|    0|    2|          347742|11.1333| null|       S|
|         10|       1|     2|Nasser, Mrs. Nich...|female|14.0|    1|    0|          237736|30.0708| null|       C|
|         11|       1|     3|Sandstrom, Miss. ...|female| 4.0|    1|    1|         PP 9549|   16.7|   G6|       S|
|         12|       1|     1|Bonnell, Miss. El...|female|58.0|    0|    0|          113783|  26.55| C103|       S|
|         13|       0|     3|Saundercock, Mr. ...|  male|20.0|    0|    0|       A/5. 2151|   8.05| null|       S|
|         14|       0|     3|Andersson, Mr. An...|  male|39.0|    1|    5|          347082| 31.275| null|       S|
|         15|       0|     3|Vestrom, Miss. Hu...|female|14.0|    0|    0|          350406| 7.8542| null|       S|
|         16|       1|     2|Hewlett, Mrs. (Ma...|female|55.0|    0|    0|          248706|   16.0| null|       S|
|         17|       0|     3|Rice, Master. Eugene|  male| 2.0|    4|    1|          382652| 29.125| null|       Q|
|         18|       1|     2|Williams, Mr. Cha...|  male|null|    0|    0|          244373|   13.0| null|       S|
|         19|       0|     3|Vander Planke, Mr...|female|31.0|    1|    0|          345763|   18.0| null|       S|
|         20|       1|     3|Masselmani, Mrs. ...|female|null|    0|    0|            2649|  7.225| null|       C|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
only showing top 20 rows

Filtrowanie operacji

In [ ]:
data = data.filter(data['Survived'] == 1)
data.show()

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+--------+-----+--------+
|PassengerId|Survived|Pclass|                Name|   Sex| Age|SibSp|Parch|          Ticket|   Price|Cabin|Embarked|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+--------+-----+--------+
|          2|       1|     1|Cumings, Mrs. Joh...|female|38.0|    1|    0|        PC 17599| 71.2833|  C85|       C|
|          3|       1|     3|Heikkinen, Miss. ...|female|26.0|    0|    0|STON/O2. 3101282|   7.925| null|       S|
|          4|       1|     1|Futrelle, Mrs. Ja...|female|35.0|    1|    0|          113803|    53.1| C123|       S|
|          9|       1|     3|Johnson, Mrs. Osc...|female|27.0|    0|    2|          347742| 11.1333| null|       S|
|         10|       1|     2|Nasser, Mrs. Nich...|female|14.0|    1|    0|          237736| 30.0708| null|       C|
|         11|       1|     3|Sandstrom, Miss. ...|female| 4.0|    1|    1|         PP 9549|    16.7|   G6|       S|
|         12|       1|     1|Bonnell, Miss. El...|female|58.0|    0|    0|          113783|   26.55| C103|       S|
|         16|       1|     2|Hewlett, Mrs. (Ma...|female|55.0|    0|    0|          248706|    16.0| null|       S|
|         18|       1|     2|Williams, Mr. Cha...|  male|null|    0|    0|          244373|    13.0| null|       S|
|         20|       1|     3|Masselmani, Mrs. ...|female|null|    0|    0|            2649|   7.225| null|       C|
|         22|       1|     2|Beesley, Mr. Lawr...|  male|34.0|    0|    0|          248698|    13.0|  D56|       S|
|         23|       1|     3|"McGowan, Miss. A...|female|15.0|    0|    0|          330923|  8.0292| null|       Q|
|         24|       1|     1|Sloper, Mr. Willi...|  male|28.0|    0|    0|          113788|    35.5|   A6|       S|
|         26|       1|     3|Asplund, Mrs. Car...|female|38.0|    1|    5|          347077| 31.3875| null|       S|
|         29|       1|     3|"O'Dwyer, Miss. E...|female|null|    0|    0|          330959|  7.8792| null|       Q|
|         32|       1|     1|Spencer, Mrs. Wil...|female|null|    1|    0|        PC 17569|146.5208|  B78|       C|
|         33|       1|     3|Glynn, Miss. Mary...|female|null|    0|    0|          335677|    7.75| null|       Q|
|         37|       1|     3|    Mamee, Mr. Hanna|  male|null|    0|    0|            2677|  7.2292| null|       C|
|         40|       1|     3|Nicola-Yarred, Mi...|female|14.0|    1|    0|            2651| 11.2417| null|       C|
|         44|       1|     2|Laroche, Miss. Si...|female| 3.0|    1|    2|   SC/Paris 2123| 41.5792| null|       C|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+--------+-----+--------+
only showing top 20 rows

In [ ]:
data = data.filter((data['Survived'] == 1) & (data['Pclass'] == 3))
data.show()

+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
|PassengerId|Survived|Pclass|                Name|   Sex| Age|SibSp|Parch|          Ticket|  Price|Cabin|Embarked|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
|          3|       1|     3|Heikkinen, Miss. ...|female|26.0|    0|    0|STON/O2. 3101282|  7.925| null|       S|
|          9|       1|     3|Johnson, Mrs. Osc...|female|27.0|    0|    2|          347742|11.1333| null|       S|
|         11|       1|     3|Sandstrom, Miss. ...|female| 4.0|    1|    1|         PP 9549|   16.7|   G6|       S|
|         20|       1|     3|Masselmani, Mrs. ...|female|null|    0|    0|            2649|  7.225| null|       C|
|         23|       1|     3|"McGowan, Miss. A...|female|15.0|    0|    0|          330923| 8.0292| null|       Q|
|         26|       1|     3|Asplund, Mrs. Car...|female|38.0|    1|    5|          347077|31.3875| null|       S|
|         29|       1|     3|"O'Dwyer, Miss. E...|female|null|    0|    0|          330959| 7.8792| null|       Q|
|         33|       1|     3|Glynn, Miss. Mary...|female|null|    0|    0|          335677|   7.75| null|       Q|
|         37|       1|     3|    Mamee, Mr. Hanna|  male|null|    0|    0|            2677| 7.2292| null|       C|
|         40|       1|     3|Nicola-Yarred, Mi...|female|14.0|    1|    0|            2651|11.2417| null|       C|
|         45|       1|     3|Devaney, Miss. Ma...|female|19.0|    0|    0|          330958| 7.8792| null|       Q|
|         48|       1|     3|O'Driscoll, Miss....|female|null|    0|    0|           14311|   7.75| null|       Q|
|         66|       1|     3|Moubarek, Master....|  male|null|    1|    1|            2661|15.2458| null|       C|
|         69|       1|     3|Andersson, Miss. ...|female|17.0|    4|    2|         3101281|  7.925| null|       S|
|         75|       1|     3|       Bing, Mr. Lee|  male|32.0|    0|    0|            1601|56.4958| null|       S|
|         80|       1|     3|Dowdell, Miss. El...|female|30.0|    0|    0|          364516| 12.475| null|       S|
|         82|       1|     3|Sheerlinck, Mr. J...|  male|29.0|    0|    0|          345779|    9.5| null|       S|
|         83|       1|     3|McDermott, Miss. ...|female|null|    0|    0|          330932| 7.7875| null|       Q|
|         86|       1|     3|Backstrom, Mrs. K...|female|33.0|    3|    0|         3101278|  15.85| null|       S|
|        107|       1|     3|Salkjelsvik, Miss...|female|21.0|    0|    0|          343120|   7.65| null|       S|
+-----------+--------+------+--------------------+------+----+-----+-----+----------------+-------+-----+--------+
only showing top 20 rows

Tworzenie pandas-on-Spark DataFrame z Spark DataFrame.

`psdf = sdf.pandas_api()`

W przypadku DataFrame, metoda plot() jest wygodnym sposobem na wykreślenie wszystkich kolumn z etykietami:

In [ ]:
# import pyspark.pandas as ps

# pser = pd.Series(np.random.randn(1000),
#                  index=pd.date_range('1/1/2000', periods=1000))
# psser = ps.Series(pser)
# psser = psser.cummax()
# psser.plot()

# pdf = pd.DataFrame(np.random.randn(1000, 4), index=pser.index,
#                    columns=['A', 'B', 'C', 'D'])
# psdf = ps.from_pandas(pdf)
# psdf = psdf.cummax()
# psdf.plot()

# SQL w PySpark

In [20]:
from datetime import date, timedelta, datetime
import time

Tworzenie nowej sesji PySpark z odpowiednimi parametrami konfiguracyjnymi

In [25]:
sc = SparkSession.builder.appName("PySparkSQL")\
    .config("spark.sql.shuffle.partitions", "50") \
    .config("spark.driver.maxResultSize","5g") \
    .config("spark.sql.execution.arrow.enabled", "true")\
    .getOrCreate()

Pobranie plików i załadowanie ich do środowiska

Dane z linku: https://www.kaggle.com/datasets/cmenca/new-york-times-hardcover-fiction-best-sellers

In [21]:
from google.colab import files
files.upload()

Output hidden; open in https://colab.research.google.com to view.

### Sposoby tworzenia ramki danych

In [26]:
#JSON
dataframe = sc.read.json('nyt2.json')

#TXT FILES
# dataframe_txt = sc.read.text('text_data.txt')

#CSV FILES
# dataframe_csv = sc.read.csv('csv_data.csv')

#PARQUET FILES
# dataframe_parquet = sc.read.load('parquet_data.parquet')

Wyświetlenie pierwszych dziesięciu rekordów

In [27]:
dataframe.show(10)

+--------------------+--------------------+--------------------+-----------------+--------------------+-------------+-----------------+-------------+----+--------------+--------------------+-------------+
|                 _id|  amazon_product_url|              author| bestsellers_date|         description|        price|   published_date|    publisher|rank|rank_last_week|               title|weeks_on_list|
+--------------------+--------------------+--------------------+-----------------+--------------------+-------------+-----------------+-------------+----+--------------+--------------------+-------------+
|{5b4aa4ead3089013...|http://www.amazon...|       Dean R Koontz|{{1211587200000}}|Odd Thomas, who c...|   {null, 27}|{{1212883200000}}|       Bantam| {1}|           {0}|           ODD HOURS|          {1}|
|{5b4aa4ead3089013...|http://www.amazon...|     Stephenie Meyer|{{1211587200000}}|Aliens have taken...|{25.99, null}|{{1212883200000}}|Little, Brown| {2}|           {1}|            THE HOST|          {3}|
|{5b4aa4ead3089013...|http://www.amazon...|        Emily Giffin|{{1211587200000}}|A woman's happy m...|{24.95, null}|{{1212883200000}}| St. Martin's| {3}|           {2}|LOVE THE ONE YOU'...|          {2}|
|{5b4aa4ead3089013...|http://www.amazon...|   Patricia Cornwell|{{1211587200000}}|A Massachusetts s...|{22.95, null}|{{1212883200000}}|       Putnam| {4}|           {0}|           THE FRONT|          {1}|
|{5b4aa4ead3089013...|http://www.amazon...|     Chuck Palahniuk|{{1211587200000}}|An aging porn que...|{24.95, null}|{{1212883200000}}|    Doubleday| {5}|           {0}|               SNUFF|          {1}|
|{5b4aa4ead3089013...|http://www.amazon...|James Patterson a...|{{1211587200000}}|A woman finds an ...|{24.99, null}|{{1212883200000}}|Little, Brown| {6}|           {3}|SUNDAYS AT TIFFANY’S|          {4}|
|{5b4aa4ead3089013...|http://www.amazon...|       John Sandford|{{1211587200000}}|The Minneapolis d...|{26.95, null}|{{1212883200000}}|       Putnam| {7}|           {4}|        PHANTOM PREY|          {3}|
|{5b4aa4ead3089013...|http://www.amazon...|       Jimmy Buffett|{{1211587200000}}|A Southern family...|{21.99, null}|{{1212883200000}}|Little, Brown| {8}|           {6}|          SWINE NOT?|          {2}|
|{5b4aa4ead3089013...|http://www.amazon...|    Elizabeth George|{{1211587200000}}|In Cornwall, tryi...|{27.95, null}|{{1212883200000}}|       Harper| {9}|           {8}|     CARELESS IN RED|          {3}|
|{5b4aa4ead3089013...|http://www.amazon...|      David Baldacci|{{1211587200000}}|An intelligence a...|{26.99, null}|{{1212883200000}}|Grand Central|{10}|           {7}|     THE WHOLE TRUTH|          {5}|
+--------------------+--------------------+--------------------+-----------------+--------------------+-------------+-----------------+-------------+----+--------------+--------------------+-------------+
only showing top 10 rows

Schemat pliku

In [28]:
dataframe.printSchema()

root
 |-- _id: struct (nullable = true)
 |    |-- $oid: string (nullable = true)
 |-- amazon_product_url: string (nullable = true)
 |-- author: string (nullable = true)
 |-- bestsellers_date: struct (nullable = true)
 |    |-- $date: struct (nullable = true)
 |    |    |-- $numberLong: string (nullable = true)
 |-- description: string (nullable = true)
 |-- price: struct (nullable = true)
 |    |-- $numberDouble: string (nullable = true)
 |    |-- $numberInt: string (nullable = true)
 |-- published_date: struct (nullable = true)
 |    |-- $date: struct (nullable = true)
 |    |    |-- $numberLong: string (nullable = true)
 |-- publisher: string (nullable = true)
 |-- rank: struct (nullable = true)
 |    |-- $numberInt: string (nullable = true)
 |-- rank_last_week: struct (nullable = true)
 |    |-- $numberInt: string (nullable = true)
 |-- title: string (nullable = true)
 |-- weeks_on_list: struct (nullable = true)
 |    |-- $numberInt: string (nullable = true)

Porównanie z klasycznymi ramkami danych w `pandas`

In [23]:
df = pd.read_json('nyt2.json', lines=True)
df.head(5)

,_id,bestsellers_date,published_date,amazon_product_url,author,description,price,publisher,title,rank,rank_last_week,weeks_on_list
0,{'$oid': '5b4aa4ead3089013507db18b'},{'$date': {'$numberLong': '1211587200000'}},{'$date': {'$numberLong': '1212883200000'}},http://www.amazon.com/Odd-Hours-Dean-Koontz/dp...,Dean R Koontz,"Odd Thomas, who can communicate with the dead,...",{'$numberInt': '27'},Bantam,ODD HOURS,{'$numberInt': '1'},{'$numberInt': '0'},{'$numberInt': '1'}
1,{'$oid': '5b4aa4ead3089013507db18c'},{'$date': {'$numberLong': '1211587200000'}},{'$date': {'$numberLong': '1212883200000'}},http://www.amazon.com/The-Host-Novel-Stephenie...,Stephenie Meyer,Aliens have taken control of the minds and bod...,{'$numberDouble': '25.99'},"Little, Brown",THE HOST,{'$numberInt': '2'},{'$numberInt': '1'},{'$numberInt': '3'}
2,{'$oid': '5b4aa4ead3089013507db18d'},{'$date': {'$numberLong': '1211587200000'}},{'$date': {'$numberLong': '1212883200000'}},http://www.amazon.com/Love-Youre-With-Emily-Gi...,Emily Giffin,A woman's happy marriage is shaken when she en...,{'$numberDouble': '24.95'},St. Martin's,LOVE THE ONE YOU'RE WITH,{'$numberInt': '3'},{'$numberInt': '2'},{'$numberInt': '2'}
3,{'$oid': '5b4aa4ead3089013507db18e'},{'$date': {'$numberLong': '1211587200000'}},{'$date': {'$numberLong': '1212883200000'}},http://www.amazon.com/The-Front-Garano-Patrici...,Patricia Cornwell,A Massachusetts state investigator and his tea...,{'$numberDouble': '22.95'},Putnam,THE FRONT,{'$numberInt': '4'},{'$numberInt': '0'},{'$numberInt': '1'}
4,{'$oid': '5b4aa4ead3089013507db18f'},{'$date': {'$numberLong': '1211587200000'}},{'$date': {'$numberLong': '1212883200000'}},http://www.amazon.com/Snuff-Chuck-Palahniuk/dp...,Chuck Palahniuk,An aging porn queens aims to cap her career by...,{'$numberDouble': '24.95'},Doubleday,SNUFF,{'$numberInt': '5'},{'$numberInt': '0'},{'$numberInt': '1'}

Usunięcie wartości zduplikowanych

In [30]:
dataframe_dropdup = dataframe.dropDuplicates()
dataframe_dropdup.show(10)

+--------------------+--------------------+--------------------+-----------------+--------------------+-------------+-----------------+----------------+----+--------------+--------------------+-------------+
|                 _id|  amazon_product_url|              author| bestsellers_date|         description|        price|   published_date|       publisher|rank|rank_last_week|               title|weeks_on_list|
+--------------------+--------------------+--------------------+-----------------+--------------------+-------------+-----------------+----------------+----+--------------+--------------------+-------------+
|{5b4aa4ead3089013...|http://www.amazon...|Clive Cussler wit...|{{1213401600000}}|Juan Cabrillo and...|{26.95, null}|{{1214697600000}}|          Putnam| {4}|           {3}|         PLAGUE SHIP|          {2}|
|{5b4aa4ead3089013...|http://www.amazon...|      Jeffery Deaver|{{1215820800000}}|Detectives Lincol...|    {null, 0}|{{1217116800000}}|Simon & Schuster|{20}|           {0}|   THE BROKEN WINDOW|          {0}|
|{5b4aa4ead3089013...|http://www.amazon...|        Daniel Silva|{{1217030400000}}|Gabriel Allon, an...|{26.95, null}|{{1218326400000}}|          Putnam| {1}|           {0}|  THE SECRET SERVANT|          {1}|
|{5b4aa4ead3089013...|http://www.amazon...|     Janet Evanovich|{{1217030400000}}|Stephanie Plum an...|{27.95, null}|{{1218326400000}}|    St. Martin’s| {9}|           {7}|   FEARLESS FOURTEEN|          {6}|
|{5b4aa4ead3089013...|http://www.amazon...|          Jane Green|{{1218240000000}}|A woman’s life ch...|    {null, 0}|{{1219536000000}}|          Viking|{18}|           {0}|     THE BEACH HOUSE|          {0}|
|{5b4aa4ead3089013...|http://www.amazon...|      Brunonia Barry|{{1220054400000}}|Secrets of a fami...|{24.95, null}|{{1221350400000}}|          Morrow|{13}|          {10}|     THE LACE READER|          {5}|
|{5b4aa4ead3089013...|http://www.amazon...|    David Wroblewski|{{1221264000000}}|A mute takes refu...|{25.95, null}|{{1222560000000}}|            Ecco| {9}|           {9}|THE STORY OF EDGA...|         {14}|
|{5b4aa4ead3089013...|http://www.amazon...|       John Sandford|{{1225497600000}}|Virgil Flowers in...|    {null, 0}|{{1226793600000}}|          Putnam|{20}|           {0}|      HEAT LIGHTNING|          {0}|
|{5b4aa4ead3089013...|http://www.amazon...|            J D Robb|{{1226102400000}}|Lt. Eve Dallas in...|{25.95, null}|{{1227398400000}}|          Putnam| {2}|           {0}|  SALVATION IN DEATH|          {1}|
|{5b4aa4ead3089013...|http://www.amazon...|       Toni Morrison|{{1226707200000}}|In 17th-century A...|{23.95, null}|{{1228003200000}}|           Knopf| {5}|           {0}|             A MERCY|          {1}|
+--------------------+--------------------+--------------------+-----------------+--------------------+-------------+-----------------+----------------+----+--------------+--------------------+-------------+
only showing top 10 rows

In [31]:
print(dataframe.count())
print(dataframe_dropdup.count())

10195
10195

Wyświetlenie kolumn z pliku

In [ ]:
dataframe.columns

### Zapytania SQL

In [32]:
dataframe.select("author").show(10) #Show all entries in title column

+--------------------+
|              author|
+--------------------+
|       Dean R Koontz|
|     Stephenie Meyer|
|        Emily Giffin|
|   Patricia Cornwell|
|     Chuck Palahniuk|
|James Patterson a...|
|       John Sandford|
|       Jimmy Buffett|
|    Elizabeth George|
|      David Baldacci|
+--------------------+
only showing top 10 rows

In [33]:
dataframe.select("author", "title", "rank", "price").show(10)  #Show all entries in title, author, rank, price

+--------------------+--------------------+----+-------------+
|              author|               title|rank|        price|
+--------------------+--------------------+----+-------------+
|       Dean R Koontz|           ODD HOURS| {1}|   {null, 27}|
|     Stephenie Meyer|            THE HOST| {2}|{25.99, null}|
|        Emily Giffin|LOVE THE ONE YOU'...| {3}|{24.95, null}|
|   Patricia Cornwell|           THE FRONT| {4}|{22.95, null}|
|     Chuck Palahniuk|               SNUFF| {5}|{24.95, null}|
|James Patterson a...|SUNDAYS AT TIFFANY’S| {6}|{24.99, null}|
|       John Sandford|        PHANTOM PREY| {7}|{26.95, null}|
|       Jimmy Buffett|          SWINE NOT?| {8}|{21.99, null}|
|    Elizabeth George|     CARELESS IN RED| {9}|{27.95, null}|
|      David Baldacci|     THE WHOLE TRUTH|{10}|{26.99, null}|
+--------------------+--------------------+----+-------------+
only showing top 10 rows

Wykorzystanie klauzuli WHEN

In [34]:
# Show title and assign 0 or 1 depending on title

dataframe.select("title", when(dataframe.title != 'ODD HOURS', 1).otherwise(0)).show(10)

+--------------------+-----------------------------------------------------+
|               title|CASE WHEN (NOT (title = ODD HOURS)) THEN 1 ELSE 0 END|
+--------------------+-----------------------------------------------------+
|           ODD HOURS|                                                    0|
|            THE HOST|                                                    1|
|LOVE THE ONE YOU'...|                                                    1|
|           THE FRONT|                                                    1|
|               SNUFF|                                                    1|
|SUNDAYS AT TIFFANY’S|                                                    1|
|        PHANTOM PREY|                                                    1|
|          SWINE NOT?|                                                    1|
|     CARELESS IN RED|                                                    1|
|     THE WHOLE TRUTH|                                                    1|
+--------------------+-----------------------------------------------------+
only showing top 10 rows

Wykorzystanie klauzuli ISIN

In [35]:
# Show rows with specified authors if in the given options

dataframe[dataframe.author.isin("John Sandford","Emily Giffin")].show(5)
print(dataframe[dataframe.author.isin("John Sandford","Emily Giffin")].count())

+--------------------+--------------------+-------------+-----------------+--------------------+-------------+-----------------+------------+----+--------------+--------------------+-------------+
|                 _id|  amazon_product_url|       author| bestsellers_date|         description|        price|   published_date|   publisher|rank|rank_last_week|               title|weeks_on_list|
+--------------------+--------------------+-------------+-----------------+--------------------+-------------+-----------------+------------+----+--------------+--------------------+-------------+
|{5b4aa4ead3089013...|http://www.amazon...| Emily Giffin|{{1211587200000}}|A woman's happy m...|{24.95, null}|{{1212883200000}}|St. Martin's| {3}|           {2}|LOVE THE ONE YOU'...|          {2}|
|{5b4aa4ead3089013...|http://www.amazon...|John Sandford|{{1211587200000}}|The Minneapolis d...|{26.95, null}|{{1212883200000}}|      Putnam| {7}|           {4}|        PHANTOM PREY|          {3}|
|{5b4aa4ead3089013...|http://www.amazon...| Emily Giffin|{{1212192000000}}|A woman’s happy m...|{24.95, null}|{{1213488000000}}|St. Martin’s| {4}|           {3}|LOVE THE ONE YOU'...|          {3}|
|{5b4aa4ead3089013...|http://www.amazon...|John Sandford|{{1212192000000}}|The Minneapolis d...|{26.95, null}|{{1213488000000}}|      Putnam| {9}|           {7}|        PHANTOM PREY|          {4}|
|{5b4aa4ead3089013...|http://www.amazon...| Emily Giffin|{{1212796800000}}|A woman’s happy m...|{24.95, null}|{{1214092800000}}|St. Martin’s| {4}|           {4}|LOVE THE ONE YOU'...|          {4}|
+--------------------+--------------------+-------------+-----------------+--------------------+-------------+-----------------+------------+----+--------------+--------------------+-------------+
only showing top 5 rows

152

Klauzula LIKE

In [36]:
# Show author and title is TRUE if title has " THE " word in titles

dataframe.select("author", "title", dataframe.title.like("% THE %")).show(15)

+--------------------+--------------------+------------------+
|              author|               title|title LIKE % THE %|
+--------------------+--------------------+------------------+
|       Dean R Koontz|           ODD HOURS|             false|
|     Stephenie Meyer|            THE HOST|             false|
|        Emily Giffin|LOVE THE ONE YOU'...|              true|
|   Patricia Cornwell|           THE FRONT|             false|
|     Chuck Palahniuk|               SNUFF|             false|
|James Patterson a...|SUNDAYS AT TIFFANY’S|             false|
|       John Sandford|        PHANTOM PREY|             false|
|       Jimmy Buffett|          SWINE NOT?|             false|
|    Elizabeth George|     CARELESS IN RED|             false|
|      David Baldacci|     THE WHOLE TRUTH|             false|
|        Troy Denning|          INVINCIBLE|             false|
|          James Frey|BRIGHT SHINY MORNING|             false|
|         Garth Stein|THE ART OF RACING...|              true|
|     Debbie Macomber|       TWENTY WISHES|             false|
|         Jeff Shaara|      THE STEEL WAVE|             false|
+--------------------+--------------------+------------------+
only showing top 15 rows

In [37]:
dataframe.select("author", "title", dataframe.title.like("THE %")).show(15)

+--------------------+--------------------+----------------+
|              author|               title|title LIKE THE %|
+--------------------+--------------------+----------------+
|       Dean R Koontz|           ODD HOURS|           false|
|     Stephenie Meyer|            THE HOST|            true|
|        Emily Giffin|LOVE THE ONE YOU'...|           false|
|   Patricia Cornwell|           THE FRONT|            true|
|     Chuck Palahniuk|               SNUFF|           false|
|James Patterson a...|SUNDAYS AT TIFFANY’S|           false|
|       John Sandford|        PHANTOM PREY|           false|
|       Jimmy Buffett|          SWINE NOT?|           false|
|    Elizabeth George|     CARELESS IN RED|           false|
|      David Baldacci|     THE WHOLE TRUTH|            true|
|        Troy Denning|          INVINCIBLE|           false|
|          James Frey|BRIGHT SHINY MORNING|           false|
|         Garth Stein|THE ART OF RACING...|            true|
|     Debbie Macomber|       TWENTY WISHES|           false|
|         Jeff Shaara|      THE STEEL WAVE|            true|
+--------------------+--------------------+----------------+
only showing top 15 rows

Klauzule STARTS-WITH i ENDS-WITH

In [38]:
dataframe.select("author", "title", dataframe.title.startswith("THE")).show(5)

+-----------------+--------------------+----------------------+
|           author|               title|startswith(title, THE)|
+-----------------+--------------------+----------------------+
|    Dean R Koontz|           ODD HOURS|                 false|
|  Stephenie Meyer|            THE HOST|                  true|
|     Emily Giffin|LOVE THE ONE YOU'...|                 false|
|Patricia Cornwell|           THE FRONT|                  true|
|  Chuck Palahniuk|               SNUFF|                 false|
+-----------------+--------------------+----------------------+
only showing top 5 rows

In [39]:
dataframe.select("author", "title", dataframe.title.endswith("NT")).show(5)

+-----------------+--------------------+-------------------+
|           author|               title|endswith(title, NT)|
+-----------------+--------------------+-------------------+
|    Dean R Koontz|           ODD HOURS|              false|
|  Stephenie Meyer|            THE HOST|              false|
|     Emily Giffin|LOVE THE ONE YOU'...|              false|
|Patricia Cornwell|           THE FRONT|               true|
|  Chuck Palahniuk|               SNUFF|              false|
+-----------------+--------------------+-------------------+
only showing top 5 rows

Wyciąganie części tekstu z kolumny

In [40]:
dataframe.select(dataframe.author.substr(1, 6).alias("auth")).show()

+------+
|  auth|
+------+
|Dean R|
|Stephe|
|Emily |
|Patric|
|Chuck |
|James |
|John S|
|Jimmy |
|Elizab|
|David |
|Troy D|
|James |
|Garth |
|Debbie|
|Jeff S|
|Philli|
|Jhumpa|
|Joseph|
|John G|
|James |
+------+
only showing top 20 rows

Zmiana nazwy kolumny w zapytaniu

In [41]:
dataframe.select(dataframe.title.substr(1,100).alias("title")).show(5)

+--------------------+
|               title|
+--------------------+
|           ODD HOURS|
|            THE HOST|
|LOVE THE ONE YOU'...|
|           THE FRONT|
|               SNUFF|
+--------------------+
only showing top 5 rows

Wyświetlenie typów danych

In [42]:
# Returns dataframe column names and data types
dataframe.dtypes

[('_id', 'struct<$oid:string>'),
 ('amazon_product_url', 'string'),
 ('author', 'string'),
 ('bestsellers_date', 'struct<$date:struct<$numberLong:string>>'),
 ('description', 'string'),
 ('price', 'struct<$numberDouble:string,$numberInt:string>'),
 ('published_date', 'struct<$date:struct<$numberLong:string>>'),
 ('publisher', 'string'),
 ('rank', 'struct<$numberInt:string>'),
 ('rank_last_week', 'struct<$numberInt:string>'),
 ('title', 'string'),
 ('weeks_on_list', 'struct<$numberInt:string>')]

In [43]:
# Displays the content of dataframe
dataframe.show()

+--------------------+--------------------+--------------------+-----------------+--------------------+-------------+-----------------+--------------------+----+--------------+--------------------+-------------+
|                 _id|  amazon_product_url|              author| bestsellers_date|         description|        price|   published_date|           publisher|rank|rank_last_week|               title|weeks_on_list|
+--------------------+--------------------+--------------------+-----------------+--------------------+-------------+-----------------+--------------------+----+--------------+--------------------+-------------+
|{5b4aa4ead3089013...|http://www.amazon...|       Dean R Koontz|{{1211587200000}}|Odd Thomas, who c...|   {null, 27}|{{1212883200000}}|              Bantam| {1}|           {0}|           ODD HOURS|          {1}|
|{5b4aa4ead3089013...|http://www.amazon...|     Stephenie Meyer|{{1211587200000}}|Aliens have taken...|{25.99, null}|{{1212883200000}}|       Little, Brown| {2}|           {1}|            THE HOST|          {3}|
|{5b4aa4ead3089013...|http://www.amazon...|        Emily Giffin|{{1211587200000}}|A woman's happy m...|{24.95, null}|{{1212883200000}}|        St. Martin's| {3}|           {2}|LOVE THE ONE YOU'...|          {2}|
|{5b4aa4ead3089013...|http://www.amazon...|   Patricia Cornwell|{{1211587200000}}|A Massachusetts s...|{22.95, null}|{{1212883200000}}|              Putnam| {4}|           {0}|           THE FRONT|          {1}|
|{5b4aa4ead3089013...|http://www.amazon...|     Chuck Palahniuk|{{1211587200000}}|An aging porn que...|{24.95, null}|{{1212883200000}}|           Doubleday| {5}|           {0}|               SNUFF|          {1}|
|{5b4aa4ead3089013...|http://www.amazon...|James Patterson a...|{{1211587200000}}|A woman finds an ...|{24.99, null}|{{1212883200000}}|       Little, Brown| {6}|           {3}|SUNDAYS AT TIFFANY’S|          {4}|
|{5b4aa4ead3089013...|http://www.amazon...|       John Sandford|{{1211587200000}}|The Minneapolis d...|{26.95, null}|{{1212883200000}}|              Putnam| {7}|           {4}|        PHANTOM PREY|          {3}|
|{5b4aa4ead3089013...|http://www.amazon...|       Jimmy Buffett|{{1211587200000}}|A Southern family...|{21.99, null}|{{1212883200000}}|       Little, Brown| {8}|           {6}|          SWINE NOT?|          {2}|
|{5b4aa4ead3089013...|http://www.amazon...|    Elizabeth George|{{1211587200000}}|In Cornwall, tryi...|{27.95, null}|{{1212883200000}}|              Harper| {9}|           {8}|     CARELESS IN RED|          {3}|
|{5b4aa4ead3089013...|http://www.amazon...|      David Baldacci|{{1211587200000}}|An intelligence a...|{26.99, null}|{{1212883200000}}|       Grand Central|{10}|           {7}|     THE WHOLE TRUTH|          {5}|
|{5b4aa4ead3089013...|http://www.amazon...|        Troy Denning|{{1211587200000}}|The New Jedi orde...|   {null, 27}|{{1212883200000}}|  Del Rey/Ballantine|{11}|           {5}|          INVINCIBLE|          {2}|
|{5b4aa4ead3089013...|http://www.amazon...|          James Frey|{{1211587200000}}|A novel, set in L...|{26.95, null}|{{1212883200000}}|              Harper|{12}|           {9}|BRIGHT SHINY MORNING|          {2}|
|{5b4aa4ead3089013...|http://www.amazon...|         Garth Stein|{{1211587200000}}|A Lab-terrier mix...|{23.95, null}|{{1212883200000}}|              Harper|{13}|           {0}|THE ART OF RACING...|          {1}|
|{5b4aa4ead3089013...|http://www.amazon...|     Debbie Macomber|{{1211587200000}}|A widow who owns ...|{24.95, null}|{{1212883200000}}|                Mira|{14}|          {10}|       TWENTY WISHES|          {4}|
|{5b4aa4ead3089013...|http://www.amazon...|         Jeff Shaara|{{1211587200000}}|A novel about the...|   {null, 28}|{{1212883200000}}|          Ballantine|{15}|          {11}|      THE STEEL WAVE|          {2}|
|{5b4aa4ead3089013...|http://www.amazon...|    Phillip Margolin|{{1211587200000}}|                    |    {null, 0}|{{1212883200000}}|HarperCollins Pub...|{16}|           {0}| EXECUTIVE PRIVILEGE|          {0}|
|{5b4aa4ead3089013...|http://www.amazon...|       Jhumpa Lahiri|{{1211587200000}}|Stories of the an...|    {null, 0}|{{1212883200000}}|               Knopf|{17}|           {0}|  UNACCUSTOMED EARTH|          {0}|
|{5b4aa4ead3089013...|http://www.amazon...|      Joseph O'Neill|{{1211587200000}}|A Dutchman desert...|    {null, 0}|{{1212883200000}}|Knopf Publishing ...|{18}|           {0}|          NETHERLAND|          {0}|
|{5b4aa4ead3089013...|http://www.amazon...|        John Grisham|{{1211587200000}}|Political and leg...|    {null, 0}|{{1212883200000}}|Doubleday Publishing|{19}|           {0}|          THE APPEAL|          {0}|
|{5b4aa4ead3089013...|http://www.amazon...|       James Rollins|{{1211587200000}}|                    |    {null, 0}|{{1212883200000}}|Random House Publ...|{20}|           {0}|INDIANA JONES AND...|          {0}|
+--------------------+--------------------+--------------------+-----------------+--------------------+-------------+-----------------+--------------------+----+--------------+--------------------+-------------+
only showing top 20 rows

Wyświetlenie pierwszych 5 wierszy

In [44]:
# Return first n rows
dataframe.head(5)

[Row(_id=Row($oid='5b4aa4ead3089013507db18b'), amazon_product_url='http://www.amazon.com/Odd-Hours-Dean-Koontz/dp/0553807056?tag=NYTBS-20', author='Dean R Koontz', bestsellers_date=Row($date=Row($numberLong='1211587200000')), description='Odd Thomas, who can communicate with the dead, confronts evil forces in a California coastal town.', price=Row($numberDouble=None, $numberInt='27'), published_date=Row($date=Row($numberLong='1212883200000')), publisher='Bantam', rank=Row($numberInt='1'), rank_last_week=Row($numberInt='0'), title='ODD HOURS', weeks_on_list=Row($numberInt='1')),
 Row(_id=Row($oid='5b4aa4ead3089013507db18c'), amazon_product_url='http://www.amazon.com/The-Host-Novel-Stephenie-Meyer/dp/0316218502?tag=NYTBS-20', author='Stephenie Meyer', bestsellers_date=Row($date=Row($numberLong='1211587200000')), description='Aliens have taken control of the minds and bodies of most humans, but one woman won’t surrender.', price=Row($numberDouble='25.99', $numberInt=None), published_date=Row($date=Row($numberLong='1212883200000')), publisher='Little, Brown', rank=Row($numberInt='2'), rank_last_week=Row($numberInt='1'), title='THE HOST', weeks_on_list=Row($numberInt='3')),
 Row(_id=Row($oid='5b4aa4ead3089013507db18d'), amazon_product_url='http://www.amazon.com/Love-Youre-With-Emily-Giffin/dp/0312348665?tag=NYTBS-20', author='Emily Giffin', bestsellers_date=Row($date=Row($numberLong='1211587200000')), description="A woman's happy marriage is shaken when she encounters an old boyfriend.", price=Row($numberDouble='24.95', $numberInt=None), published_date=Row($date=Row($numberLong='1212883200000')), publisher="St. Martin's", rank=Row($numberInt='3'), rank_last_week=Row($numberInt='2'), title="LOVE THE ONE YOU'RE WITH", weeks_on_list=Row($numberInt='2')),
 Row(_id=Row($oid='5b4aa4ead3089013507db18e'), amazon_product_url='http://www.amazon.com/The-Front-Garano-Patricia-Cornwell-ebook/dp/B0017T0C9M?tag=NYTBS-20', author='Patricia Cornwell', bestsellers_date=Row($date=Row($numberLong='1211587200000')), description='A Massachusetts state investigator and his team from "At Risk" confront a rogue association of municipal police departments.', price=Row($numberDouble='22.95', $numberInt=None), published_date=Row($date=Row($numberLong='1212883200000')), publisher='Putnam', rank=Row($numberInt='4'), rank_last_week=Row($numberInt='0'), title='THE FRONT', weeks_on_list=Row($numberInt='1')),
 Row(_id=Row($oid='5b4aa4ead3089013507db18f'), amazon_product_url='http://www.amazon.com/Snuff-Chuck-Palahniuk/dp/0385517882?tag=NYTBS-20', author='Chuck Palahniuk', bestsellers_date=Row($date=Row($numberLong='1211587200000')), description='An aging porn queens aims to cap her career by having sex on film with 600 men in one day.', price=Row($numberDouble='24.95', $numberInt=None), published_date=Row($date=Row($numberLong='1212883200000')), publisher='Doubleday', rank=Row($numberInt='5'), rank_last_week=Row($numberInt='0'), title='SNUFF', weeks_on_list=Row($numberInt='1'))]

Wyświetlenie pierwszego wiersza

In [45]:
# Returns first row
dataframe.first()

Row(_id=Row($oid='5b4aa4ead3089013507db18b'), amazon_product_url='http://www.amazon.com/Odd-Hours-Dean-Koontz/dp/0553807056?tag=NYTBS-20', author='Dean R Koontz', bestsellers_date=Row($date=Row($numberLong='1211587200000')), description='Odd Thomas, who can communicate with the dead, confronts evil forces in a California coastal town.', price=Row($numberDouble=None, $numberInt='27'), published_date=Row($date=Row($numberLong='1212883200000')), publisher='Bantam', rank=Row($numberInt='1'), rank_last_week=Row($numberInt='0'), title='ODD HOURS', weeks_on_list=Row($numberInt='1'))

In [46]:
# Return first n rows
dataframe.take(5)

[Row(_id=Row($oid='5b4aa4ead3089013507db18b'), amazon_product_url='http://www.amazon.com/Odd-Hours-Dean-Koontz/dp/0553807056?tag=NYTBS-20', author='Dean R Koontz', bestsellers_date=Row($date=Row($numberLong='1211587200000')), description='Odd Thomas, who can communicate with the dead, confronts evil forces in a California coastal town.', price=Row($numberDouble=None, $numberInt='27'), published_date=Row($date=Row($numberLong='1212883200000')), publisher='Bantam', rank=Row($numberInt='1'), rank_last_week=Row($numberInt='0'), title='ODD HOURS', weeks_on_list=Row($numberInt='1')),
 Row(_id=Row($oid='5b4aa4ead3089013507db18c'), amazon_product_url='http://www.amazon.com/The-Host-Novel-Stephenie-Meyer/dp/0316218502?tag=NYTBS-20', author='Stephenie Meyer', bestsellers_date=Row($date=Row($numberLong='1211587200000')), description='Aliens have taken control of the minds and bodies of most humans, but one woman won’t surrender.', price=Row($numberDouble='25.99', $numberInt=None), published_date=Row($date=Row($numberLong='1212883200000')), publisher='Little, Brown', rank=Row($numberInt='2'), rank_last_week=Row($numberInt='1'), title='THE HOST', weeks_on_list=Row($numberInt='3')),
 Row(_id=Row($oid='5b4aa4ead3089013507db18d'), amazon_product_url='http://www.amazon.com/Love-Youre-With-Emily-Giffin/dp/0312348665?tag=NYTBS-20', author='Emily Giffin', bestsellers_date=Row($date=Row($numberLong='1211587200000')), description="A woman's happy marriage is shaken when she encounters an old boyfriend.", price=Row($numberDouble='24.95', $numberInt=None), published_date=Row($date=Row($numberLong='1212883200000')), publisher="St. Martin's", rank=Row($numberInt='3'), rank_last_week=Row($numberInt='2'), title="LOVE THE ONE YOU'RE WITH", weeks_on_list=Row($numberInt='2')),
 Row(_id=Row($oid='5b4aa4ead3089013507db18e'), amazon_product_url='http://www.amazon.com/The-Front-Garano-Patricia-Cornwell-ebook/dp/B0017T0C9M?tag=NYTBS-20', author='Patricia Cornwell', bestsellers_date=Row($date=Row($numberLong='1211587200000')), description='A Massachusetts state investigator and his team from "At Risk" confront a rogue association of municipal police departments.', price=Row($numberDouble='22.95', $numberInt=None), published_date=Row($date=Row($numberLong='1212883200000')), publisher='Putnam', rank=Row($numberInt='4'), rank_last_week=Row($numberInt='0'), title='THE FRONT', weeks_on_list=Row($numberInt='1')),
 Row(_id=Row($oid='5b4aa4ead3089013507db18f'), amazon_product_url='http://www.amazon.com/Snuff-Chuck-Palahniuk/dp/0385517882?tag=NYTBS-20', author='Chuck Palahniuk', bestsellers_date=Row($date=Row($numberLong='1211587200000')), description='An aging porn queens aims to cap her career by having sex on film with 600 men in one day.', price=Row($numberDouble='24.95', $numberInt=None), published_date=Row($date=Row($numberLong='1212883200000')), publisher='Doubleday', rank=Row($numberInt='5'), rank_last_week=Row($numberInt='0'), title='SNUFF', weeks_on_list=Row($numberInt='1'))]

Opis wartości w tabeli

In [47]:
# Computes summary statistics
dataframe.describe().show()

+-------+--------------------+---------------+--------------------+---------+------------------+
|summary|  amazon_product_url|         author|         description|publisher|             title|
+-------+--------------------+---------------+--------------------+---------+------------------+
|  count|               10195|          10195|               10195|    10195|             10195|
|   mean|                null|           null|                null|     null|1877.7142857142858|
| stddev|                null|           null|                null|     null| 370.9760613506458|
|    min|http://www.amazon...|        AJ Finn|                    |      ACE|  10TH ANNIVERSARY|
|    max|https://www.amazo...|various authors|’Tis for the Rebe...|allantine|               ZOO|
+-------+--------------------+---------------+--------------------+---------+------------------+

Ilość elementów w tabeli, liczone po rekordach

In [48]:
# Counts the number of rows in dataframe
dataframe.count()

10195

In [49]:
# Counts the number of distinct rows in dataframe
dataframe.distinct().count()

10195

In [50]:
# Prints plans including physical and logical
dataframe.explain()

== Physical Plan ==
FileScan json [_id#31,amazon_product_url#32,author#33,bestsellers_date#34,description#35,price#36,published_date#37,publisher#38,rank#39,rank_last_week#40,title#41,weeks_on_list#42] Batched: false, DataFilters: [], Format: JSON, Location: InMemoryFileIndex[file:/content/nyt2.json], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<_id:struct<$oid:string>,amazon_product_url:string,author:string,bestsellers_date:struct<$d...


Funkcja explain w PySpark służy do wyświetlenia planu wykonawczego dla zapytania DataFrame. Plan wykonawczy to szczegółowy opis tego, jak Spark planuje przetworzyć dane dla danej operacji. Pozwala to na zrozumienie kroków, jakie Spark podejmuje w celu wykonania zapytania i analizy potencjalnych problemów związanych z wydajnością.

### Rodzaje Planu Wykonawczego:
* Physical Plan (Fizyczny Plan): Fizyczny plan wykonawczy opisuje, jak Spark planuje faktyczne operacje przetwarzania danych w klastrze. Zawiera informacje o konkretnej implementacji i kolejności operacji.

* Optimized Plan (Zoptymalizowany Plan): Zoptymalizowany plan wykonawczy jest krokiem po planie fizycznym i obejmuje optymalizacje przeprowadzone przez katalizator Sparka. Może zawierać informacje o usunięciu zbędnych operacji lub przekształceniach.

### Co Pokazuje Plan Wykonawczy:
Plan wykonawczy zawiera informacje takie jak:

* Fazy Wykonawcze: (np. Scan, Filter, Aggregate).
* Operacje: (np. Project, Join, GroupBy).
* Typy Operacji: (np. SortMergeJoin, HashAggregate).
* Struktury Danych Używane w Operacjach: (np. DataFrame, RDD).
* Kroki Przetwarzania na Poszczególnych Węzłach Klastra.
* Schemat Kolumn.
* Wykorzystywane Indeksy.
* Informacje o Partycjonowaniu i Shufflingu.

### Interpretacja Planu Wykonawczego:
* Exchange hashpartitioning: Oznacza, że planuje operację wymiany danych między węzłami klastra.
* HashAggregate: Wskazuje na operację agregacji z wykorzystaniem funkcji skrótu (hash).
* Scan ExistingRDD: Oznacza, że dane są wczytywane z istniejącego RDD.


Dzięki explain można zrozumieć, w jaki sposób Spark przetwarza zapytanie, co jest szczególnie przydatne podczas optymalizacji wydajności w bardziej zaawansowanych scenariuszach.

# Dodawanie, aktualizowanie i usuwanie kolumn

Dodawanie kolumny

In [51]:
# Lit() is required while we are creating columns with exact values.

dataframe = dataframe.withColumn('new_column', lit('This is a new column'))
dataframe.show(5)

+--------------------+--------------------+-----------------+-----------------+--------------------+-------------+-----------------+-------------+----+--------------+--------------------+-------------+--------------------+
|                 _id|  amazon_product_url|           author| bestsellers_date|         description|        price|   published_date|    publisher|rank|rank_last_week|               title|weeks_on_list|          new_column|
+--------------------+--------------------+-----------------+-----------------+--------------------+-------------+-----------------+-------------+----+--------------+--------------------+-------------+--------------------+
|{5b4aa4ead3089013...|http://www.amazon...|    Dean R Koontz|{{1211587200000}}|Odd Thomas, who c...|   {null, 27}|{{1212883200000}}|       Bantam| {1}|           {0}|           ODD HOURS|          {1}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|  Stephenie Meyer|{{1211587200000}}|Aliens have taken...|{25.99, null}|{{1212883200000}}|Little, Brown| {2}|           {1}|            THE HOST|          {3}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|     Emily Giffin|{{1211587200000}}|A woman's happy m...|{24.95, null}|{{1212883200000}}| St. Martin's| {3}|           {2}|LOVE THE ONE YOU'...|          {2}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|Patricia Cornwell|{{1211587200000}}|A Massachusetts s...|{22.95, null}|{{1212883200000}}|       Putnam| {4}|           {0}|           THE FRONT|          {1}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|  Chuck Palahniuk|{{1211587200000}}|An aging porn que...|{24.95, null}|{{1212883200000}}|    Doubleday| {5}|           {0}|               SNUFF|          {1}|This is a new column|
+--------------------+--------------------+-----------------+-----------------+--------------------+-------------+-----------------+-------------+----+--------------+--------------------+-------------+--------------------+
only showing top 5 rows

Aktualizacja nazwy kolumny

In [52]:
# Update column 'amazon_product_url' with 'URL'

dataframe = dataframe.withColumnRenamed('amazon_product_url', 'URL')
dataframe.show(5)

+--------------------+--------------------+-----------------+-----------------+--------------------+-------------+-----------------+-------------+----+--------------+--------------------+-------------+--------------------+
|                 _id|                 URL|           author| bestsellers_date|         description|        price|   published_date|    publisher|rank|rank_last_week|               title|weeks_on_list|          new_column|
+--------------------+--------------------+-----------------+-----------------+--------------------+-------------+-----------------+-------------+----+--------------+--------------------+-------------+--------------------+
|{5b4aa4ead3089013...|http://www.amazon...|    Dean R Koontz|{{1211587200000}}|Odd Thomas, who c...|   {null, 27}|{{1212883200000}}|       Bantam| {1}|           {0}|           ODD HOURS|          {1}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|  Stephenie Meyer|{{1211587200000}}|Aliens have taken...|{25.99, null}|{{1212883200000}}|Little, Brown| {2}|           {1}|            THE HOST|          {3}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|     Emily Giffin|{{1211587200000}}|A woman's happy m...|{24.95, null}|{{1212883200000}}| St. Martin's| {3}|           {2}|LOVE THE ONE YOU'...|          {2}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|Patricia Cornwell|{{1211587200000}}|A Massachusetts s...|{22.95, null}|{{1212883200000}}|       Putnam| {4}|           {0}|           THE FRONT|          {1}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|  Chuck Palahniuk|{{1211587200000}}|An aging porn que...|{24.95, null}|{{1212883200000}}|    Doubleday| {5}|           {0}|               SNUFF|          {1}|This is a new column|
+--------------------+--------------------+-----------------+-----------------+--------------------+-------------+-----------------+-------------+----+--------------+--------------------+-------------+--------------------+
only showing top 5 rows

Usuwanie kolumn - sposób pierwszy

In [53]:
dataframe_remove = dataframe.drop("publisher", "published_date").show(5)

+--------------------+--------------------+-----------------+-----------------+--------------------+-------------+----+--------------+--------------------+-------------+--------------------+
|                 _id|                 URL|           author| bestsellers_date|         description|        price|rank|rank_last_week|               title|weeks_on_list|          new_column|
+--------------------+--------------------+-----------------+-----------------+--------------------+-------------+----+--------------+--------------------+-------------+--------------------+
|{5b4aa4ead3089013...|http://www.amazon...|    Dean R Koontz|{{1211587200000}}|Odd Thomas, who c...|   {null, 27}| {1}|           {0}|           ODD HOURS|          {1}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|  Stephenie Meyer|{{1211587200000}}|Aliens have taken...|{25.99, null}| {2}|           {1}|            THE HOST|          {3}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|     Emily Giffin|{{1211587200000}}|A woman's happy m...|{24.95, null}| {3}|           {2}|LOVE THE ONE YOU'...|          {2}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|Patricia Cornwell|{{1211587200000}}|A Massachusetts s...|{22.95, null}| {4}|           {0}|           THE FRONT|          {1}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|  Chuck Palahniuk|{{1211587200000}}|An aging porn que...|{24.95, null}| {5}|           {0}|               SNUFF|          {1}|This is a new column|
+--------------------+--------------------+-----------------+-----------------+--------------------+-------------+----+--------------+--------------------+-------------+--------------------+
only showing top 5 rows

Usuwanie kolumn - sposób drugi

In [54]:
dataframe_remove2 = dataframe.drop(dataframe.publisher).drop(dataframe.published_date).show(5)

+--------------------+--------------------+-----------------+-----------------+--------------------+-------------+----+--------------+--------------------+-------------+--------------------+
|                 _id|                 URL|           author| bestsellers_date|         description|        price|rank|rank_last_week|               title|weeks_on_list|          new_column|
+--------------------+--------------------+-----------------+-----------------+--------------------+-------------+----+--------------+--------------------+-------------+--------------------+
|{5b4aa4ead3089013...|http://www.amazon...|    Dean R Koontz|{{1211587200000}}|Odd Thomas, who c...|   {null, 27}| {1}|           {0}|           ODD HOURS|          {1}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|  Stephenie Meyer|{{1211587200000}}|Aliens have taken...|{25.99, null}| {2}|           {1}|            THE HOST|          {3}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|     Emily Giffin|{{1211587200000}}|A woman's happy m...|{24.95, null}| {3}|           {2}|LOVE THE ONE YOU'...|          {2}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|Patricia Cornwell|{{1211587200000}}|A Massachusetts s...|{22.95, null}| {4}|           {0}|           THE FRONT|          {1}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|  Chuck Palahniuk|{{1211587200000}}|An aging porn que...|{24.95, null}| {5}|           {0}|               SNUFF|          {1}|This is a new column|
+--------------------+--------------------+-----------------+-----------------+--------------------+-------------+----+--------------+--------------------+-------------+--------------------+
only showing top 5 rows

Klauzula GROUPBY

In [55]:
dataframe.groupBy("rank_last_week")

In [56]:
# Group by author, count the books of the authors in the groups
dataframe.groupBy("rank_last_week").count().show()

+--------------+-----+
|rank_last_week|count|
+--------------+-----+
|           {7}|  470|
|          {10}|  363|
|          {15}|  123|
|          {11}|  327|
|           {4}|  524|
|           {3}|  520|
|          {12}|  289|
|           {6}|  497|
|          {13}|  246|
|           {8}|  460|
|          {14}|  171|
|          {16}|   53|
|           {0}| 4174|
|           {2}|  526|
|           {9}|  421|
|           {1}|  529|
|           {5}|  502|
+--------------+-----+

Uzupełnianie brakujących wartości

In [57]:
# Replace null values
dataframe.na.fill(50).show(20)

+--------------------+--------------------+--------------------+-----------------+--------------------+-------------+-----------------+--------------------+----+--------------+--------------------+-------------+--------------------+
|                 _id|                 URL|              author| bestsellers_date|         description|        price|   published_date|           publisher|rank|rank_last_week|               title|weeks_on_list|          new_column|
+--------------------+--------------------+--------------------+-----------------+--------------------+-------------+-----------------+--------------------+----+--------------+--------------------+-------------+--------------------+
|{5b4aa4ead3089013...|http://www.amazon...|       Dean R Koontz|{{1211587200000}}|Odd Thomas, who c...|   {null, 27}|{{1212883200000}}|              Bantam| {1}|           {0}|           ODD HOURS|          {1}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|     Stephenie Meyer|{{1211587200000}}|Aliens have taken...|{25.99, null}|{{1212883200000}}|       Little, Brown| {2}|           {1}|            THE HOST|          {3}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|        Emily Giffin|{{1211587200000}}|A woman's happy m...|{24.95, null}|{{1212883200000}}|        St. Martin's| {3}|           {2}|LOVE THE ONE YOU'...|          {2}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|   Patricia Cornwell|{{1211587200000}}|A Massachusetts s...|{22.95, null}|{{1212883200000}}|              Putnam| {4}|           {0}|           THE FRONT|          {1}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|     Chuck Palahniuk|{{1211587200000}}|An aging porn que...|{24.95, null}|{{1212883200000}}|           Doubleday| {5}|           {0}|               SNUFF|          {1}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|James Patterson a...|{{1211587200000}}|A woman finds an ...|{24.99, null}|{{1212883200000}}|       Little, Brown| {6}|           {3}|SUNDAYS AT TIFFANY’S|          {4}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|       John Sandford|{{1211587200000}}|The Minneapolis d...|{26.95, null}|{{1212883200000}}|              Putnam| {7}|           {4}|        PHANTOM PREY|          {3}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|       Jimmy Buffett|{{1211587200000}}|A Southern family...|{21.99, null}|{{1212883200000}}|       Little, Brown| {8}|           {6}|          SWINE NOT?|          {2}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|    Elizabeth George|{{1211587200000}}|In Cornwall, tryi...|{27.95, null}|{{1212883200000}}|              Harper| {9}|           {8}|     CARELESS IN RED|          {3}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|      David Baldacci|{{1211587200000}}|An intelligence a...|{26.99, null}|{{1212883200000}}|       Grand Central|{10}|           {7}|     THE WHOLE TRUTH|          {5}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|        Troy Denning|{{1211587200000}}|The New Jedi orde...|   {null, 27}|{{1212883200000}}|  Del Rey/Ballantine|{11}|           {5}|          INVINCIBLE|          {2}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|          James Frey|{{1211587200000}}|A novel, set in L...|{26.95, null}|{{1212883200000}}|              Harper|{12}|           {9}|BRIGHT SHINY MORNING|          {2}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|         Garth Stein|{{1211587200000}}|A Lab-terrier mix...|{23.95, null}|{{1212883200000}}|              Harper|{13}|           {0}|THE ART OF RACING...|          {1}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|     Debbie Macomber|{{1211587200000}}|A widow who owns ...|{24.95, null}|{{1212883200000}}|                Mira|{14}|          {10}|       TWENTY WISHES|          {4}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|         Jeff Shaara|{{1211587200000}}|A novel about the...|   {null, 28}|{{1212883200000}}|          Ballantine|{15}|          {11}|      THE STEEL WAVE|          {2}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|    Phillip Margolin|{{1211587200000}}|                    |    {null, 0}|{{1212883200000}}|HarperCollins Pub...|{16}|           {0}| EXECUTIVE PRIVILEGE|          {0}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|       Jhumpa Lahiri|{{1211587200000}}|Stories of the an...|    {null, 0}|{{1212883200000}}|               Knopf|{17}|           {0}|  UNACCUSTOMED EARTH|          {0}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|      Joseph O'Neill|{{1211587200000}}|A Dutchman desert...|    {null, 0}|{{1212883200000}}|Knopf Publishing ...|{18}|           {0}|          NETHERLAND|          {0}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|        John Grisham|{{1211587200000}}|Political and leg...|    {null, 0}|{{1212883200000}}|Doubleday Publishing|{19}|           {0}|          THE APPEAL|          {0}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|       James Rollins|{{1211587200000}}|                    |    {null, 0}|{{1212883200000}}|Random House Publ...|{20}|           {0}|INDIANA JONES AND...|          {0}|This is a new column|
+--------------------+--------------------+--------------------+-----------------+--------------------+-------------+-----------------+--------------------+----+--------------+--------------------+-------------+--------------------+
only showing top 20 rows

In [58]:
# Return new dataframe restricting rows with null values
dataframe.na.drop().show(5)

+--------------------+--------------------+-----------------+-----------------+--------------------+-------------+-----------------+-------------+----+--------------+--------------------+-------------+--------------------+
|                 _id|                 URL|           author| bestsellers_date|         description|        price|   published_date|    publisher|rank|rank_last_week|               title|weeks_on_list|          new_column|
+--------------------+--------------------+-----------------+-----------------+--------------------+-------------+-----------------+-------------+----+--------------+--------------------+-------------+--------------------+
|{5b4aa4ead3089013...|http://www.amazon...|    Dean R Koontz|{{1211587200000}}|Odd Thomas, who c...|   {null, 27}|{{1212883200000}}|       Bantam| {1}|           {0}|           ODD HOURS|          {1}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|  Stephenie Meyer|{{1211587200000}}|Aliens have taken...|{25.99, null}|{{1212883200000}}|Little, Brown| {2}|           {1}|            THE HOST|          {3}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|     Emily Giffin|{{1211587200000}}|A woman's happy m...|{24.95, null}|{{1212883200000}}| St. Martin's| {3}|           {2}|LOVE THE ONE YOU'...|          {2}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|Patricia Cornwell|{{1211587200000}}|A Massachusetts s...|{22.95, null}|{{1212883200000}}|       Putnam| {4}|           {0}|           THE FRONT|          {1}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|  Chuck Palahniuk|{{1211587200000}}|An aging porn que...|{24.95, null}|{{1212883200000}}|    Doubleday| {5}|           {0}|               SNUFF|          {1}|This is a new column|
+--------------------+--------------------+-----------------+-----------------+--------------------+-------------+-----------------+-------------+----+--------------+--------------------+-------------+--------------------+
only showing top 5 rows

In [59]:
# Return new dataframe replacing one value with another
dataframe.na.replace('Dean R Koontz', 'Dean Koontz').show(5)

+--------------------+--------------------+-----------------+-----------------+--------------------+-------------+-----------------+-------------+----+--------------+--------------------+-------------+--------------------+
|                 _id|                 URL|           author| bestsellers_date|         description|        price|   published_date|    publisher|rank|rank_last_week|               title|weeks_on_list|          new_column|
+--------------------+--------------------+-----------------+-----------------+--------------------+-------------+-----------------+-------------+----+--------------+--------------------+-------------+--------------------+
|{5b4aa4ead3089013...|http://www.amazon...|      Dean Koontz|{{1211587200000}}|Odd Thomas, who c...|   {null, 27}|{{1212883200000}}|       Bantam| {1}|           {0}|           ODD HOURS|          {1}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|  Stephenie Meyer|{{1211587200000}}|Aliens have taken...|{25.99, null}|{{1212883200000}}|Little, Brown| {2}|           {1}|            THE HOST|          {3}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|     Emily Giffin|{{1211587200000}}|A woman's happy m...|{24.95, null}|{{1212883200000}}| St. Martin's| {3}|           {2}|LOVE THE ONE YOU'...|          {2}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|Patricia Cornwell|{{1211587200000}}|A Massachusetts s...|{22.95, null}|{{1212883200000}}|       Putnam| {4}|           {0}|           THE FRONT|          {1}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|  Chuck Palahniuk|{{1211587200000}}|An aging porn que...|{24.95, null}|{{1212883200000}}|    Doubleday| {5}|           {0}|               SNUFF|          {1}|This is a new column|
+--------------------+--------------------+-----------------+-----------------+--------------------+-------------+-----------------+-------------+----+--------------+--------------------+-------------+--------------------+
only showing top 5 rows

Partycjonowanie

In [60]:
# Dataframe with 10 partitions

dataframe.repartition(10).rdd.getNumPartitions()

10

In [61]:
# Dataframe with 1 partition

dataframe.coalesce(1).rdd.getNumPartitions()

1

Liczba partycji w PySpark ma istotny wpływ na jakość i wydajność obliczeń. Partycje to podziały na fragmenty danych, które są przetwarzane równolegle na różnych węzłach klastra. Odpowiednie zarządzanie liczbą partycji jest kluczowe, ponieważ może wpływać na równomierność obciążenia klastra, szybkość przetwarzania, oraz zużycie zasobów.

Oto kilka aspektów, które należy wziąć pod uwagę:

1. Równomierność Obciążenia:
* Zalety: Większa liczba partycji może prowadzić do równomierniejszego rozkładu obciążenia między węzłami klastra. To oznacza, że każdy węzeł będzie miał mniej pracy do wykonania, co przyspiesza przetwarzanie.

* Wady: Zbyt duża liczba partycji może prowadzić do nadmiernego narzutu komunikacyjnego między węzłami, co może zrównoważyć korzyści z równomiernego obciążenia.

2. Wydajność Przetwarzania:
* Zalety: Większa liczba partycji może zwiększyć wydajność przetwarzania równoległego, zwłaszcza w przypadku operacji, które można efektywnie parallelizować.

* Wady: Zbyt duża liczba partycji może prowadzić do nadmiernego narzutu związanego z zarządzaniem partycjami oraz wymianą danych między węzłami.

3. Zużycie Pamięci:
* Zalety: Mniejsza liczba partycji może zmniejszyć zużycie pamięci, ponieważ dla każdej partycji wymagane są pewne zasoby.

* Wady: Zbyt mała liczba partycji może prowadzić do nierównomiernego rozkładu obciążenia oraz ograniczonej równoległości przetwarzania.

4. Zasoby Klastra:
* Zalety: Dostosowanie liczby partycji do dostępnych zasobów klastra może przynieść optymalne wyniki.

* Wady: Nieprawidłowe dostosowanie liczby partycji może prowadzić do nieefektywnego wykorzystania dostępnych zasobów.

Jak Wybrać Odpowiednią Liczbę Partycji:
* Zrozumienie Danych: Przemyśl, jak są rozproszone dane, aby dostosować liczbę partycji do specyfiki zbioru danych.
* Rozmiar Partycji: W przypadku dużych zbiorów danych warto dostosować rozmiar partycji do dostępnej pamięci na węzłach klastra.
* Narzut Komunikacyjny: Optymalizuj liczbę partycji tak, aby unikać nadmiernego narzutu komunikacyjnego.
* Monitorowanie Wydajności: Regularnie monitoruj wydajność aplikacji i dostosuj liczbę partycji w zależności od wyników.

Ostateczny wybór liczby partycji zależy od charakterystyki danych, dostępnych zasobów klastra oraz konkretnego rodzaju operacji, które są wykonywane. Warto eksperymentować i monitorować wydajność, aby dostosować liczbę partycji do konkretnych potrzeb.

### Wykonanie kodu SQL na ramce danych

Pierwszy krok to nadanie nazwy dla tabeli, by móc się do niej odnosić w zapytaniach SQL

In [62]:
# Registering a table
dataframe.registerTempTable("df")

Zapytanie podstawowe

In [63]:
sc.sql("select * from df").show(3)

+--------------------+--------------------+---------------+-----------------+--------------------+-------------+-----------------+-------------+----+--------------+--------------------+-------------+--------------------+
|                 _id|                 URL|         author| bestsellers_date|         description|        price|   published_date|    publisher|rank|rank_last_week|               title|weeks_on_list|          new_column|
+--------------------+--------------------+---------------+-----------------+--------------------+-------------+-----------------+-------------+----+--------------+--------------------+-------------+--------------------+
|{5b4aa4ead3089013...|http://www.amazon...|  Dean R Koontz|{{1211587200000}}|Odd Thomas, who c...|   {null, 27}|{{1212883200000}}|       Bantam| {1}|           {0}|           ODD HOURS|          {1}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|Stephenie Meyer|{{1211587200000}}|Aliens have taken...|{25.99, null}|{{1212883200000}}|Little, Brown| {2}|           {1}|            THE HOST|          {3}|This is a new column|
|{5b4aa4ead3089013...|http://www.amazon...|   Emily Giffin|{{1211587200000}}|A woman's happy m...|{24.95, null}|{{1212883200000}}| St. Martin's| {3}|           {2}|LOVE THE ONE YOU'...|          {2}|This is a new column|
+--------------------+--------------------+---------------+-----------------+--------------------+-------------+-----------------+-------------+----+--------------+--------------------+-------------+--------------------+
only showing top 3 rows

Zapytanie bardziej złożone

In [64]:
sc.sql("select \
               CASE WHEN description LIKE '%love%' THEN 'Love_Theme' \
               WHEN description LIKE '%hate%' THEN 'Hate_Theme' \
               WHEN description LIKE '%happy%' THEN 'Happiness_Theme' \
               WHEN description LIKE '%anger%' THEN 'Anger_Theme' \
               WHEN description LIKE '%horror%' THEN 'Horror_Theme' \
               WHEN description LIKE '%death%' THEN 'Criminal_Theme' \
               WHEN description LIKE '%detective%' THEN 'Mystery_Theme' \
               ELSE 'Other_Themes' \
               END Themes \
       from df").groupBy('Themes').count().show()

sc.sql("select \
        CASE WHEN description LIKE '%love%' THEN 'Love_Theme' \
        ELSE 'Other_Themes' \
        END Themes \
  from df").groupBy('Themes').count().show()

+---------------+-----+
|         Themes|count|
+---------------+-----+
|    Anger_Theme|  203|
|   Other_Themes| 8778|
|  Mystery_Theme|  454|
|     Hate_Theme|   23|
| Criminal_Theme|  305|
|   Horror_Theme|    6|
|Happiness_Theme|   34|
|     Love_Theme|  392|
+---------------+-----+

+------------+-----+
|      Themes|count|
+------------+-----+
|Other_Themes| 9803|
|  Love_Theme|  392|
+------------+-----+

### Konwersja struktur danych

In [65]:
# Converting dataframe into a RDD of string
dataframe.toJSON().first()

'{"_id":{"$oid":"5b4aa4ead3089013507db18b"},"URL":"http://www.amazon.com/Odd-Hours-Dean-Koontz/dp/0553807056?tag=NYTBS-20","author":"Dean R Koontz","bestsellers_date":{"$date":{"$numberLong":"1211587200000"}},"description":"Odd Thomas, who can communicate with the dead, confronts evil forces in a California coastal town.","price":{"$numberInt":"27"},"published_date":{"$date":{"$numberLong":"1212883200000"}},"publisher":"Bantam","rank":{"$numberInt":"1"},"rank_last_week":{"$numberInt":"0"},"title":"ODD HOURS","weeks_on_list":{"$numberInt":"1"},"new_column":"This is a new column"}'

In [66]:
# Obtaining contents of df as Pandas dataFrame
dataframe.toPandas()

/content/spark-3.1.1-bin-hadoop3.2/python/pyspark/sql/pandas/conversion.py:87: UserWarning: toPandas attempted Arrow optimization because 'spark.sql.execution.arrow.pyspark.enabled' is set to true; however, failed by the reason below:
  Nested StructType not supported in conversion to Arrow
Attempting non-optimization as 'spark.sql.execution.arrow.pyspark.fallback.enabled' is set to true.
  warnings.warn(msg)

,_id,URL,author,bestsellers_date,description,price,published_date,publisher,rank,rank_last_week,title,weeks_on_list,new_column
0,"(5b4aa4ead3089013507db18b,)",http://www.amazon.com/Odd-Hours-Dean-Koontz/dp...,Dean R Koontz,"((1211587200000,),)","Odd Thomas, who can communicate with the dead,...","(None, 27)","((1212883200000,),)",Bantam,"(1,)","(0,)",ODD HOURS,"(1,)",This is a new column
1,"(5b4aa4ead3089013507db18c,)",http://www.amazon.com/The-Host-Novel-Stephenie...,Stephenie Meyer,"((1211587200000,),)",Aliens have taken control of the minds and bod...,"(25.99, None)","((1212883200000,),)","Little, Brown","(2,)","(1,)",THE HOST,"(3,)",This is a new column
2,"(5b4aa4ead3089013507db18d,)",http://www.amazon.com/Love-Youre-With-Emily-Gi...,Emily Giffin,"((1211587200000,),)",A woman's happy marriage is shaken when she en...,"(24.95, None)","((1212883200000,),)",St. Martin's,"(3,)","(2,)",LOVE THE ONE YOU'RE WITH,"(2,)",This is a new column
3,"(5b4aa4ead3089013507db18e,)",http://www.amazon.com/The-Front-Garano-Patrici...,Patricia Cornwell,"((1211587200000,),)",A Massachusetts state investigator and his tea...,"(22.95, None)","((1212883200000,),)",Putnam,"(4,)","(0,)",THE FRONT,"(1,)",This is a new column
4,"(5b4aa4ead3089013507db18f,)",http://www.amazon.com/Snuff-Chuck-Palahniuk/dp...,Chuck Palahniuk,"((1211587200000,),)",An aging porn queens aims to cap her career by...,"(24.95, None)","((1212883200000,),)",Doubleday,"(5,)","(0,)",SNUFF,"(1,)",This is a new column
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10190,"(5b4aa4ead3089013507dd959,)",https://www.amazon.com/Clancy-Line-Sight-Jack-...,Mike Maden,"((1530921600000,),)",Jack Ryan Jr. risks his life to protect a woma...,"(None, 0)","((1532217600000,),)",Putnam,"(11,)","(6,)",TOM CLANCY LINE OF SIGHT,"(4,)",This is a new column
10191,"(5b4aa4ead3089013507dd95a,)",https://www.amazon.com/Something-Water-Novel-C...,Catherine Steadman,"((1530921600000,),)",A documentary filmmaker and an investment bank...,"(None, 0)","((1532217600000,),)",Ballantine,"(12,)","(11,)",SOMETHING IN THE WATER,"(5,)",This is a new column
10192,"(5b4aa4ead3089013507dd95b,)",https://www.amazon.com/Little-Fires-Everywhere...,Celeste Ng,"((1530921600000,),)",An artist upends a quiet town outside Cleveland.,"(None, 0)","((1532217600000,),)",Penguin Press,"(13,)","(12,)",LITTLE FIRES EVERYWHERE,"(41,)",This is a new column
10193,"(5b4aa4ead3089013507dd95c,)",https://www.amazon.com/Shelter-Place-Nora-Robe...,Nora Roberts,"((1530921600000,),)",Survivors of a mass shooting outside a mall in...,"(None, 0)","((1532217600000,),)",St. Martin's,"(14,)","(5,)",SHELTER IN PLACE,"(6,)",This is a new column
10194,"(5b4aa4ead3089013507dd95d,)",https://www.amazon.com/Last-Time-Lied-Novel/dp...,Riley Sager,"((1530921600000,),)",A painter is in danger when she returns to the...,"(None, 0)","((1532217600000,),)",Dutton,"(15,)","(0,)",THE LAST TIME I LIED,"(1,)",This is a new column

### Zapis do plików

In [ ]:
# Write & Save File in .parquet format
dataframe.select("author", "title", "rank", "description")\
.write \
.save("Rankings_Descriptions.parquet")

In [ ]:
# Write & Save File in .json format
dataframe.select("author", "title") \
.write \
.save("Authors_Titles.json",format="json")

### Kończenie sesji Spark

In [ ]:
# End Spark Session
sc.stop()

### Lista zadań do wykonania na zbiorze danych titanic

1. Obliczyć ile osób przeżyło
2. Obliczyć procent osób które przeżyły
3. Obliczyć średni wiek pasażerów
4. Obliczyć procentowo i liczbowo ilość pasażerów korzystających z różnych klas podróży (Pclass)
5. Określić, czy więcej było kobiet czy mężczyzn na statku
6. Obliczyć medianę i odchylenie standardowe ceny biletu
7. Wskazać ile najwięcej osób znajdowało się w jednej kabinie na statku
8. Obliczyć wariancję ceny biletów oraz percentyle 10 i 90 (funkcje z pakietu numpy)
9. Wyszukać mężczyzn w przedziale wiekowym 20-40 i zliczyć ich ilość
10. Wyszukać kobiety mające mniej niż 20 i więcej niż 40 lat i zliczyć ich ilość
11. Wypisać nazwiska osób, których długość nazwiska jest parzysta
  * Pobrać imiona i nazwiska do listy
  * W pętli dla każdej osoby
      * Podzielić tekst za pomocą znaku przecinka – funkcja split
      * Zapisać 1 element z powstałej listy
      *	Sprawdzić czy jego długość jest parzysta
      * Jeśli tak, wypisać to nazwisko
12. Na podstawie zadania 11 policzyć ilość osób z imieniem William
13. 3 swoje zapytania do bazy o innej treści niż powyżej